MyCoRe-Org/mir

.gitignore, .travis.yml, README.md, mir-it/pom.xml, mir-module/pom.xml, mir-module/src/main/java/org/mycore/mir/common/MIRCoreVersion.java, mir-module/src/main/resources-filtered/org/mycore/mir/version.properties, mir-wizard/pom.xml, pom.xml
initial merge to get git stuff working
=> MIR-526 Git-Migration

mir-it/pom.xml, mir-wizard/pom.xml, pom.xml
Update plugin version and direct dependencies
=> MIR-528 Update dependencies

mir-layout/pom.xml, mir-layout/src/main/java/org/mycore/mir/sass/resources/MIRSassResource.java, mir-layout/src/main/java/org/mycore/mir/viewer/MIRViewerConfigurationStrategy.java, mir-module/pom.xml, mir-module/src/main/java/org/mycore/mir/viewer/MIRViewerACLProvider.java, pom.xml
implemented changes for jersey update and move of mycore-viewer
=> MIR-530 Update dependencies mycore-2016.07-SNAPSHOT

mir-module/pom.xml, mir-module/src/main/java/org/mycore/mir/common/MIRCoreVersion.java, mir-module/src/main/java/org/mycore/restapi/v1/mir/MIRInfo.java, mir-module/src/main/java/org/mycore/restapi/v1/mir/package-info.java, mir-module/src/main/resources-filtered/org/mycore/mir/version.properties
same improvements as in MCR-1465
REST URI: /api/v1/mir/version
=> MIR-539 MIRCoreVersion Git Improvments

mir-module/src/main/resources/xsl/response-mir.xsl
- removed decoder from facet url
=> MIR-542 Loose filter when searching after filtering search with facets

mir-cli/src/main/config/solr-home/conf/schema.xml, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/mir-solr.xsl
=> Revert "MIR-529 added new dynamic field mods.part.{id}"

mir-layout/src/main/less/common/mir_browse.less, mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
=> MIR-535 break file name in file browser if to long

mir-module/src/main/resources/META-INF/resources/js/mir/base.js
- added regex to prevent multiple ".*"
=> MIR-357 fix person browsing

mir-it/src/test/java/org/mycore/mir/it/model/MIRIdentifier.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRAdminEditorITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRTestData.java, mir-module/src/main/java/org/mycore/mir/validation/MIRValidationHelper.java, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/editor/xeditor2mods.xsl
- added MIRValidationHelper
- added PPN validation to xEditor
=> MIR-559 validate PPN in xEditor

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/modsdetails-external.xsl
- added "download as zip" for guest users
- fixed some i18n
=> MIR-570 action "download as zip" is missing

mir-layout/src/main/java/org/mycore/mir/sass/resources/MIRSassResource.java, mir-module/src/main/java/org/mycore/mir/statistics/StatisticsResource.java, mir-module/src/main/java/org/mycore/restapi/v1/mir/MIRInfo.java
added @MCRStaticContent to compatible resources
=> MIR-571 add @MCRStaticContent to compatible resources

mir-layout/src/main/less/common/mir_metadata.less, mir-module/src/main/resources/xsl/metadata/mir-video.js.xsl
- added panel around videoplayer and videochooser, for better visibility
=> MIR-548 User failed to see video selection box

.travis.yml
removed Dwebdriver.firefox.marionette=false parameter
=> MIR-583 fix Travis for Firefox 52 ESR

mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/xsl/response-mir.xsl
fixed solr exception when using search button after browsing leads
=> MIR-580 Using search button after browsing leads to solr exception

mir-module/src/main/resources/xsl/response-mir.xsl
added editor as cooporation to result list
=> MIR-585 If editor is cooporation, it is missing in result list

mir-layout/src/main/less/common/mir_metadata.less, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
added state badge to metadata view
=> MIR-581 show state badge on metadata view

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
and also switch to GET method and fixed onChange event
=> MIR-600 use DataCites link-based content type requests

mir-module/src/test/resources/META-INF/persistence.xml, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardInitDatabase.java, mir-wizard/src/test/resources/META-INF/persistence.xml
added required changes for hibernate update.
=> MCR-1525 Hibernate update

mir-module/src/main/java/org/mycore/mir/impexp/MIRClassificationMapper.java
fixed NumberFormatException while importing PPNs
=> MIR-602 getting NumberFormatException while importing PPNs

.travis.yml, mir-it/pom.xml
- added chrome to travis.yml
- upgraded Selenium-Utils to 0.6
=> MIR-604 Upgrade Selenium-Utils to 0.6 and use Chrome with Travis

mir-wizard/src/main/resources/config/mir-wizard/mycore.properties
=> MCR-1487 Editor Framework removed

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
added validation to embargo date
=> MIR-609 Incomplete embargo date leads to NullPointerException: temporal

mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs
=> MIR-611 Can not delete files in folders

mir-module/src/main/resources/config/mir/mycore.properties
set deletion policy to 'persistent'
=> MCR-1608 removed MCRDeletedItemManager

mir-it/pom.xml, mir-layout/package.json, mir-module/package.json, mir-wizard/package.json, pom.xml
- removed maven build warnings
=> MIR-574 remove maven build warnings

mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js, mir-module/src/test/java/org/mycore/mir/authorization/accesskeys/TestAccessKeys.java, mir-module/src/test/java/org/mycore/mymaker/mir/MCRActionMappingTest.java, mir-wizard/src/test/java/org/mycore/mir/wizard/TestCommands.java
=> MIR-544 remove deprecated method usages

mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardGenerateJPAConfig.java, mir-wizard/src/main/resources/setup/dbtypes.xml
include MariaDB and remove DB2 and update JDBC drivers
=> MIR-622 update DB information fir mir-wizard

mir-module/pom.xml, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration2017_06.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mycoreobject-migrate-urn.xsl
- added migrate command to read URN from derivate and put it in a mods:identifier
=> MIR-547 migrate command for URN

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
=> MIR-630 Publication period for journals in badge contains question marks

mir-layout/src/main/resources/xsl/mir-flatmir-layout-utils.xsl, mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/metadata/mods-metadata.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
=> MIR-634 fix search issues

mir-it/src/test/integration/resources/META-INF/persistence.xml, mir-module/pom.xml, mir-wizard/src/main/resources/setup/template-persistence.xml, pom.xml
when MCR-1674 is closed no mycore-urn will disappear in MIR
=> MIR-644 remove mycore-urn dependency

mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl
=> MIR-646 can delete files in derivate with URN

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
=> MIR-650 Badges in metadata view works inconsistent

mir-module/GruntFile.js
=> MIR-659 source maps do not include sources

mir-module/src/main/resources/xsl/response-mir.xsl
- fixed badge in search result
=> MIR-656 Wrong badge in search result

mir-module/src/main/resources/xsl/response-mir.xsl
- fixed Object link on upload page
=> MIR-651 Object link on upload page doesn't work

mir-module/src/main/resources/META-INF/resources/editor/editor-admins.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/mir/xeditor-form.js, mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl, mir-module/src/main/resources/xsl/editor/xeditor2mods.xsl
- added new field for managed Identifier
=> MIR-647 can't add other identifiers if URN is generated

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mods2datacite.xsl, mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
=> MIR-662 use marcrelator and mir_institutes for better datacite support

mir-layout/src/main/less/common/mir_metadata.less, mir-module/GruntFile.js, mir-module/src/main/resources/META-INF/resources/js/mir/citation.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
added alert when citation can not be loaded from datacite
=> MIR-667 show alert when citation can not be loaded from datacite

mir-module/src/main/resources/config/mir/mycore.properties
use property MCR.PI.MetadataManager.MODSURN from mycore-mods instead
=> MCR-1725 removed MCR.PI.Inscriber.DefaultModsURN property

mir-module/src/main/resources/config/mir/mycore.properties
=> MIR-671 add 'institute' OAI Set

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
dc:contributor only add contributors fith role defined in thesis:role
=> MIR-657 add DOI and Handle Support

mir-layout/src/main/less/common/mir_metadata.less, mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/modsdetails-external.xsl
added confirmation modal befor register PI
=> MIR-666 add confirmation modal befor register PI

mir-module/src/main/java/org/mycore/mir/imageware/MIRImageWarePacker.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRSwordIngester.java
Fix compile errors caused by this MyCoRe change
=> MCR-1657 improve code quality of MCRMetadataManager

mir-module/src/main/resources/xsl/metadata/mods-metadata.xsl, mir-module/yarn.lock
mods.part was used as a sort field which is multivalued
updated yarn.lock as old version caused errors
=> MIR-679 fix new version listing on blocked or deleted documents

mir-module/src/main/resources/xsl/xsl-output-html.fragment, mir-webapp/src/main/resources/xsl/xsl-output-html.fragment
=> MCR-1752 delete xsl-output-html.fragment

mir-layout/src/main/less/common/mir_details.less
=> MIR-680 abstract is flickering when metadata page is loading

mir-layout/package.json, mir-layout/yarn.lock, mir-module/GruntFile.js, mir-module/package.json, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl, mir-module/yarn.lock
- ol.js and ol.css only get loaded when needed
- get openlayers with yarn on build time
- updated openlayers to 4.6.4
- updated bootstrap to 3.3.7
=> MIR-695 load openlayers javascript only if needed

mir-module/src/main/resources/META-INF/resources/js/mir/base.js
remove readmore class if readmore-active is set via javascript
=> MIR-704 read more link for abstract is missing

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
- added support for more than one genre for hit list
- added support for more than one genre for metadata page
=> MIR-699 Support for more than one genre is missing

mir-wizard/src/main/java/org/mycore/mir/wizard/utils/MIRWizardUnzip.java
unzip now also creates parent directories transitively
=> MIR-151 create SOLR directory in wizard

mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/metadata/mir-viewer.xsl
-readded check for mycore-viewer is displayable
-added i18n for "Vorschau"
=> MIR-703 mir-viewer div is created for non PDF derivates

mir-module/package.json, mir-module/yarn.lock
- updated bootstrap-datepicker to 1.7.1
=> MIR-706 date popup is brocken

mir-module/src/main/resources/META-INF/resources/js/mir/citation.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
- added message if service is not available
- moved full error message to console
- fixed default citation form not showing
=> MIR-707 Get "internal server error 500"

mir-module/src/main/resources/META-INF/resources/js/mir/base.js
- added ppn will now be resolved with ajax
=> MIR-708 Resolve PPNs to final page in metadata view

mir-module/src/main/resources/META-INF/resources/editor/editor-genres.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
added managed identifier fields to genre editors
=> MIR-719 managed identifier field is missing

mir-module/src/main/resources/META-INF/resources/js/mir/base.js
added function to remove XSL.Status.Message and XSL.Status.Style Parameter from URL
=> MIR-718 Remove parameter XSL.Status.Message & XSL.Status.Style from url

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
removed @xlink:href from related Item field
=> MIR-725 Show all related Items, even without href

mir-it/pom.xml, pom.xml
jetty update required for new dependencies of mycore
=> update servlet container

mir-layout/src/main/less/common/mir_details.less, mir-layout/src/main/less/common/mir_metadata.less, mir-module/GruntFile.js, mir-module/package.json, mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl, mir-module/yarn.lock
=> MIR-721 "read more" link at abstract is always shown

mir-module/src/main/resources/META-INF/resources/js/mir/xeditor-form.js, mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl
disabled all managed identifier
=> MIR-722 Can edit pi identifier in xeditor if there is more than one pi

mir-common-resources/src/main/resources/META-INF/resources/css/fileupload.css, mir-common-resources/src/main/resources/META-INF/resources/js/fileupload/fileupload.js, mir-common-resources/src/main/resources/config/mir-common-resources/messages_de.properties, mir-common-resources/src/main/resources/config/mir-common-resources/messages_en.properties, mir-common-resources/src/main/resources/xsl/fileupload.xsl, mir-layout/src/main/less/common/fileupload.less, mir-webapp/pom.xml, pom.xml
applets are not supported anymore by a majority of browsers
=> MIR-685 remove fileupload-applet support

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
related to MyCoRe-Ticket [MCR-1858](https://mycore.atlassian.net/browse/MCR-1858).
=> MCR-1858 added ogl license support

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
=> MIR-734 Choose publication does'nt work correctly

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
- enabled related item select button for related item from type host
- disabled title field after related item is selected
=> MIR-739 Can't change relatedItem

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_details.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss
=> MIR-738 abstract view for html abstract is broken

.travis.yml
firefox >56 tend to crash in travis
=> set firefox version to 56.0 to reduce crashes

mir-cli/src/main/config/acl/defaultrules-commands.txt, mir-cli/src/main/config/setup-commands.txt, mir-it/src/test/java/org/mycore/mir/it/controller/MIREditorController.java, mir-it/src/test/java/org/mycore/mir/it/controller/MIRModsEditorController.java, mir-it/src/test/java/org/mycore/mir/it/model/MIRLanguage.java, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss, mir-module/GruntFile.js, mir-module/package.json, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/mir/xeditor-form.js, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl, mir-module/src/main/resources/xsl/mods2dc-mode-dc.xsl, mir-module/src/main/resources/xsl/mods2dc.xsl, mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl, mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl, mir-module/yarn.lock, mir-wizard/src/main/resources/META-INF/resources/wizard/index.xed, mir-wizard/src/main/resources/setup/classifications.xml, mir-wizard/src/main/resources/setup/defaultrules-wizard-commands.xml
- replaced rfc4646 by rfc5646
- added select2 for language selects
- mir now requires an additional core for classifications
=> MIR-677 replace rfc4646 by rfc5646 and include all languages

.travis.yml
Leave that open, until I resolve travis issues with the current build
=> Travis-FIX

mir-module/src/main/resources/META-INF/resources/content/publish/index.xml, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/import/crossref2mods.xsl, mir-module/src/main/resources/xsl/import/datacite2mods.xsl, mir-module/src/main/resources/xsl/import/gbv-mods2mods.xsl, mir-module/src/main/resources/xsl/import/genre2genre.xsl, mir-module/src/main/resources/xsl/import/ieee2mods.xsl, mir-module/src/main/resources/xsl/import/jop2mods.xsl, mir-module/src/main/resources/xsl/import/lobid2mods.xsl, mir-module/src/main/resources/xsl/import/mods2mycoreobject.xsl, mir-module/src/main/resources/xsl/import/pubmed2mods.xsl, mir-module/src/main/resources/xsl/import/scopus2mods.xsl, mir-module/src/main/resources/xsl/import/zdb2mods.xsl
You can test it for example using:
http://localhost:8291/mir/editor/editor-admins.xed?type=doi&modsId=10.1126/science.aau5138
http://localhost:8291/mir/editor/editor-admins.xed?type=ppn&modsId=894232932
=> MIR-764 add enrichment resolver configuration and stylesheets

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-758).
=> MIR-758 fixed xMetadissPlus issues

mir-module/src/main/java/org/mycore/mir/importer/JSON2XMLTransformer.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/convertjson.xsl, mir-module/src/main/resources/xsl/import/lobid2mods.xsl, mir-module/src/main/resources/xsl/import/oadoi2mods.xsl, mir-module/src/main/resources/xsl/import/simplify-json-xml.xsl, mir-module/src/main/resources/xsl/import/zdb2mods.xsl, mir-module/src/main/resources/xsl/strip-namespaces.xsl
You have to configure MIR.OADOI.Mail.Address= and json2xml transformer for testing.
=> MIR-764 fixed lang classification and added oadoi resolver

mir-module/src/main/resources/META-INF/resources/content/search/complex.xed, mir-module/src/main/resources/META-INF/resources/content/search/complex_intern.xed, mir-module/src/main/resources/META-INF/resources/content/search/simple.xed, mir-module/src/main/resources/META-INF/resources/content/search/simple_intern.xed, mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js, mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-autocomplete.js, mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js, mir-module/src/main/resources/META-INF/resources/js/mir/xeditor-form.js, mir-module/src/main/resources/xsl/datatable.xsl
- changend glyphicons to font awesome
- fixed some bugs related to glyphicon change
=> MIR-773 glyphicons are still used in javascript

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
prefer user edited URN and DOI on export
=> MIR-771 keep dc:identifer and ddb:identifier in right order

mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
- added thumbnails in basket view
- changed thumbnails in list view
=> MIR-777 Thumbnail in basket view is missing

mir-module/src/main/resources/META-INF/resources/editor/editor-admins-includes.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-admins.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-dynamic.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-genres.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-hosts.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-xml.xed
=> MIR-765 Use xed:preload to simplify includes

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-824).
=> MIR-824 removed if statement - was for backward compatibility

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-824).
=> MIR-824 move institute repeater to editor stylesheet

mir-module/src/main/resources/xsl/import/zdb2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-829).
=> MIR-829 - improved date check and do not include invalid dates

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-831).
=> MIR-831 - make shariff buttons configurable via properties

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
=> MIR-833 Mark large dropdown lists with class to allow binding javascript

mir-module/src/main/resources/actionmappings.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-835).
=> MIR-835 - added search collection to action mapping

mir-module/src/main/resources/xsl/import/crossref2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-838).
=> MIR-838 skip empty persons in crossref stylesheet

mir-module/src/main/java/org/mycore/mir/orcid/MIROrcidServlet.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-837).
=> MIR-837 fixed mods:name/@type to personal

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-839).
=> MIR-839 use MCR.mir-module.MailSender as default mail address

mir-module/src/main/resources/xsl/metadata/mir-viewer.xsl
[Link to jira](https://mycore.atlassian.net/browse/MCR-2062).
=> MCR-2062 add changes for epub viewer

mir-module/src/main/java/org/mycore/mir/orcid/MIROrcidServlet.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/import/crossref2mods.xsl
=> merge 2018.06

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/bootstrap4fix.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/helper.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_browse.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_results.scss, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/xsl/basket-objects.xsl, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
Added some colours for the badges.
Each batch should have a colour now, but I did not thought about which one.
Furthermore I fixed the empty search in the navbar.
By the way I added some comments to the base.js:
I had trouble to understand the code and left some of my findings.
[Link to jira](https://mycore.atlassian.net/browse/MIR-842).
=> MIR-842 fix layout issues caused by bootsrap 4 migration

mir-module/src/main/resources/xsl/response-person.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-817).
=> MIR-817 remove duplicate html id (is invalid)

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/base.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/bootstrap4fix.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_results.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/print.scss, mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl, mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl, mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl, mir-module/src/main/resources/xsl/metadata/mir-file-upload.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-842).
=> MIR-842 fixed print view and file listing (only works with ff atm)

mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-850).
=> MIR-850 do not pass asterisk to viewer search

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/import/crossref2mods.xsl, mir-module/src/main/resources/xsl/import/genre2genre.xsl, mir-module/src/main/resources/xsl/import/remove-genres.xsl
=> MIR-848 copy crossrefimport from ubo

mir-module/src/main/resources/xsl/response-mir.xsl
... generated search fields from mycoreobject-dynamicfields.xsl
[Link to jira](https://mycore.atlassian.net/browse/MCR-2099).
=> MCR-2099 rename derivate search field maindoc to prevent problems with

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/import/crossref2mods.xsl, mir-module/src/main/resources/xsl/import/genre2genre.xsl, mir-module/src/main/resources/xsl/import/remove-genres.xsl
MIR-848 copy crossrefimport from ubo. [Link to jira](https://mycore.atlassian.net/browse/MIR-848).
=> Merge 2018.06 to 2019.06

mir-module/src/main/resources/xsl/xeditor-mir-templates.xsl
=> MIR-842 migrate XEditor templates to BS 4

mir-module/pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-2016).
=> MCR-2016 remove also xml-apis dependency here

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-841).
=> MIR-841 Improve multiple ids in admineditor with jquery.search-entity.js

.travis.yml
=> update geckodriver to 0.26.0

mir-module/pom.xml, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-2119).
=> MCR-2119 update dependencies

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-2119).
=> MCR-2119 fixed tomcat dependency

mir-module/pom.xml, mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreenCollectionProvider.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRGoobiCollectionProvider.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRGoobiIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIROJSCollectionProvider.java, mir-module/src/main/java/org/mycore/mir/sword2/MIROJSIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRSwordCollectionProvider.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRSwordIngesterBase.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/config/mir/solr/main/solr-schema.json, mir-module/src/main/resources/xsl/sword/jats2mods.xsl, mir-module/src/main/resources/xsl/sword/ojsmets2mods.xsl
[MIR-855](https://mycore.atlassian.net/browse/MIR-855) and [MIR-858](https://mycore.atlassian.net/browse/MIR-858).
=> MIR-858 MIR-855 add sword support for ojs and deep green

mir-layout/yarn.lock, mir-module/package.json, mir-module/yarn.lock, mir-wizard/yarn.lock
[Link to jira](https://mycore.atlassian.net/browse/MIR-859).
=> MIR-859 security fixes

mir-cli/pom.xml, mir-layout/pom.xml, mir-module/pom.xml, mir-wizard/pom.xml, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-2125).
Requires https://github.com/MyCoRe-Org/mycore/pull/889
=> MCR-2125 update dependencies

mir-layout/package.json, mir-layout/yarn.lock, mir-module/package.json, mir-module/yarn.lock
[Link to jira](https://mycore.atlassian.net/browse/MIR-863).
=> MIR-863 Upgrade Bootstrap and Fontawesome

mir-layout/package.json, mir-layout/yarn.lock, mir-module/package.json, mir-module/yarn.lock
=> merge 2019.06

mir-module/src/main/resources/META-INF/resources/config/navigation.xml, mir-module/src/main/resources/xsl/layout/mir-navigation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-864).
=> MIR-864 hide change user contact if not editable

mir-module/src/main/resources/xsl/user.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-2136).
=> MCR-2136 edit user link is shown even if user is not editable

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-865).
=> MIR-865 fix UnAPI URL to query K10Plus

mir-module/src/main/resources/config/mir/solr/main/solr-config.json
[Link to jira](https://mycore.atlassian.net/browse/MIR-866).
=> MIR-866 removed mods.dateIssued.host as sort criteria

mir-module/src/main/resources/xsl/sword/jats2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-867).
=> MIR-867 Fix bugs in JATS2MODS mapping

mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyManager.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2080).
=> MCR-2080 make user attributes repeatable

mir-wizard/src/main/resources/setup/dbtypes.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-872).
=> MIR-872 - fix driver URL, central.maven.org doesn't work any longer

mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
=> MIR-870 Added class to mark select as large

mir-layout/src/main/resources/xsl/mir-flatmir-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-2151).
=> MCR-2151 added msie alert info

mir-module/src/main/resources/xsl/layout/mir-navigation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-888).
=> MIR-888 fixes losing classes for active property nav entry

mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-889).
=> MIR-889 fix classes for current user menu entry

mir-module/src/main/resources/xsl/sword/jats2mods.xsl
added function to prevent duplicated journals in JATS2MODS
[Link to jira](https://mycore.atlassian.net/browse/MIR-887).
=> MIR-887 add function to prevent duplicated journals in JATS2MODS

mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl
prevents generation of multivalue fields that should not be multivalued for a specific case
[Link to jira](https://mycore.atlassian.net/browse/MIR-884).
=> MIR-884 do not call template for relatedItem recursively

mir-module/src/main/resources/xsl/layout/mir-navigation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-890).
=> MIR-890 adds template for generating explicit footer menu entries

mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl, mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl, pom.xml
=> merge 2018.06.0.x

mir-it/pom.xml, mir-it/src/test/integration/mycore.properties, mir-it/src/test/java/org/mycore/mir/it/controller/MIRSearchController.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRAdminEditorITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRComplexSearchITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRITBase.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-895).
=> MIR-895 make mir-it tests more robust on index changes

mir-it/pom.xml, mir-it/src/test/integration/mycore.properties, mir-it/src/test/java/org/mycore/mir/it/controller/MIRSearchController.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRAdminEditorITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRComplexSearchITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRITBase.java, pom.xml
=> rebase 2019.06.x

mir-it/src/test/integration/mycore.properties, mir-it/src/test/java/org/mycore/mir/it/tests/MIRAdminEditorITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRITBase.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-895).
=> MIR-895 increase timeout and use index version

mir-module/src/main/java/org/mycore/mir/authorization/MirSelfRegistrationServlet.java
=> MIR-896 fix ClassCastException on delete of mailtoken attribute

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/base.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/bootstrap4fix.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_main_nav.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_results.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_top_nav.scss, mir-layout/src/main/resources/xsl/mir-flatmir-layout-utils.xsl, mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js, mir-module/src/main/resources/xsl/basket-objects.xsl, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl, mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl, mir-module/src/main/resources/xsl/layout/mir-navigation.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/relatedItem-subselect.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-893).
Changes are more than optimizing main menu, but it's about making dropdown menu bootstrap 4 conform. We can drop a lot of styles by using the defaults from the bootstrap and bootswatch theme.
This has probably an impact to existing applications.
=> MIR-893 makes dropdown bs4 conform and removes proprietary styles

mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyManager.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-899).
=> MIR-899 fix deletion of access key

mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-900).
=> MIR-900 apply toc.field template only once

mir-layout/src/main/resources/xsl/mir-flatmir-layout-utils.xsl, mir-layout/src/main/resources/xsl/mir-flatmir-layout.xsl, mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-894).
- changes doctype to html (5)
- removes some script declarations
- fixes invalid aria attribute
=> MIR-894 changes doctype to html and removes script type attributes

mir-module/src/main/resources/META-INF/resources/js/mir/mycore2orcid.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-902).
=> MCR-902 use message properties in orcid javascript

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_results.scss, mir-module/src/main/resources/META-INF/resources/js/mir/mycore2orcid.js, mir-module/src/main/resources/xsl/response-mir.xsl, mir-module/src/main/resources/xsl/user-orcid-oauth.xsl, mir-module/src/main/resources/xsl/user.xsl
... "display: inline-block;" statement (display: block; is right here
and already set for div elements
[Link to jira](https://mycore.atlassian.net/browse/MIR-905).
=> MIR-905 check for empty message properties and fix layout bug caused by

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/src/main/java/org/mycore/mir/MIRStateServlet.java, mir-module/src/main/resources/META-INF/web-fragment.xml, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/metadata/mir-workflow.xsl, mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/workflow-util.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-904).
=> MIR-904 some workflow for mir

mir-layout/package.json, mir-layout/yarn.lock, mir-module/package.json, mir-module/yarn.lock, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-906).
=> MIR-906 update dependencies (wip)

mir-module/src/main/java/org/mycore/mir/sword2/MIRDisseminCollectionProvider.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRSwordMetadataProvider.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/sword/dissemin-mods2mycore-mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-886).
=> MIR-886 added dissemin sword implementation and stylesheets

mir-module/src/main/resources/xsl/metadata/mir-epusta.xsl
=> MIR-907 fix date computing -1year

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/src/main/resources/META-INF/resources/js/mir/toc-layout.js, mir-module/src/main/resources/config/mir/solr/main/solr-schema.json, mir-module/src/main/resources/toc-layouts.xml, mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl, mir-module/src/main/resources/xsl/toc/mycoreobject-toc.xsl, mir-module/src/main/resources/xsl/toc/render-toc.xsl, mir-module/src/main/resources/xsl/toc/solr-facets2toc.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl, mir-module/src/main/resources/xsl/toc/toc-layouts2solr-json-facet-query.xsl
make field to get descendants configurable, see toc-layouts.xml
=> MIR-903 Refactor table of contents feature

mir-layout/package.json, mir-layout/yarn.lock, mir-module/src/main/resources/xsl/toc/render-toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-909).
=> MIR-909 update to jquery 3.5.1 and fixed value of toc expanded variable

.travis.yml, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/pom.xml, mir-module/src/main/resources/META-INF/resources/js/mir/citation.js, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-638).
=> MIR-638 use mycore-csl for citations

mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-913).
=> MIR-913 Fix layout of Blog TOCs

mir-module/src/main/resources/xsl/toc/mycoreobject-toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-912).
=> MIR-912 Add debug mode for table of contents

mir-module/src/main/resources/xsl/sword/jats2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-914).
=> MIR-914 minor fixes for jats2 mods mapping

mir-module/src/main/resources/xsl/metadata/mir-workflow.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/workflow-util.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-910).
=> MIR-910 workflow finetuning

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/toc/solr-facets2toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-920).
=> MIR-920 Fix intermediate levels (volume, issue) not linked to object

mir-layout/src/main/java/org/mycore/mir/viewer/MIRViewerBoxTransformer.java, mir-layout/src/main/resources/config/mir-layout/mycore.properties, mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-917).
=> MIR-917 add information in viewer full screen view

mir-module/src/main/resources/xsl/mir-PPN-import.xsl, mir-module/src/main/resources/xsl/mods2pica3.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-876).
work in progress, please do not merge yet
only for testing and review atm
=> MIR-876 initial version for new k10+ import stylesheet

mir-layout/src/main/resources/META-INF/resources/mir-layout/js/cosmol.js, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/cosmol/lib/main_nav.scss, mir-layout/src/main/resources/xsl/mir-cosmol-layout-utils.xsl, mir-layout/src/main/resources/xsl/mir-cosmol-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-916).
=> MIR-916 updates responsive behaviour

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-911).
=> MIR-911 remove old toc version from metadata view (was deprecated)

mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl, mir-module/src/main/resources/xsl/toc/render-toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-922).
=> MIR-922 added enclosing div for toc and missing volume information

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/base.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/bootstrap4fix.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/user-login.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/cosmol/lib/main_nav.scss, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl, mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-854).
=> MIR-854 layout bugs caused by bootstrap 4 migration

mir-module/src/main/resources/META-INF/resources/js/mir/citation.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-923).
=> MIR-923 citation select box value is not restored on page load

mir-layout/src/main/java/org/mycore/mir/viewer/MIRViewerConfigurationStrategy.java, mir-layout/src/main/resources/config/mir-layout/mycore.properties, mir-layout/src/main/resources/xsl/mir-cosmol-layout.xsl, mir-layout/src/main/resources/xsl/mir-flatmir-layout.xsl, mir-module/src/main/resources/xsl/user-orcid-oauth.xsl, mir-wizard/src/main/resources/xsl/mir-wizard-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-925).
=> MIR-925 set default of MIR.DefaultLayout.CSS uniformly to "flatly.min"

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/toc-layouts.xml, mir-module/src/main/resources/xsl/toc/toc-layouts2solr-json-facet-query.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-927).
=> MIR-927 Make TOC facet limits configurable

mir-module/src/main/resources/xsl/mir-PPN-import.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-876).
=> advance PPN mods Import

mir-module/src/main/resources/xsl/mir-PPN-import.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-876).
=> MIR-876 fix wrong class name

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
fixed genre loading
[Link to jira](https://mycore.atlassian.net/browse/MIR-930).
=> MIR-930 subselect for relatedItem does not resolve mods.type

mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js, mir-module/src/main/resources/xsl/metadata/mir-file-upload.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-795).
=> MIR-795 always upload to open folder

mir-it/src/test/java/org/mycore/mir/it/controller/MIREditorController.java, mir-it/src/test/java/org/mycore/mir/it/controller/MIRModsEditorController.java, mir-module/GruntFile.js, mir-module/package.json, mir-module/pom.xml, mir-module/src/main/java/org/mycore/mir/editor/MIREditorUtils.java, mir-module/src/main/java/org/mycore/mir/editor/MIRPostProcessor.java, mir-module/src/main/java/org/mycore/mir/editor/MIRUnescapeResolver.java, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/ckeditor-config.js, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl, mir-module/src/main/resources/xsl/editor/xeditor2mods.xsl, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/yarn.lock, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-924).
=> MIR-924 abstract html handling is wrong

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js, mir-module/src/main/resources/META-INF/resources/js/mir/xeditor-form.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-926).
=> MIR-926 PID search in admin editor is a little bit buggy

mir-module/src/main/resources/META-INF/resources/js/mir/toc-layout.js
reformatted code
[Link to jira](https://mycore.atlassian.net/browse/MIR-931).
=> MIR-931 fix CSS selector

mir-module/src/main/java/org/mycore/mir/editor/MIREditorUtils.java, mir-module/src/main/java/org/mycore/mir/editor/MIRPostProcessor.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-924).
=> MIR-924 do not prettyprint html

mir-module/src/main/resources/xsl/mycoreobject-podcast.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-918).
=> MIR-918 support mods:abstract with HTML elements

mir-module/src/main/resources/xsl/mods2marcxml.xsl
added datafield 773
fixed title indicator
replaced xsl:text by xsl:value-of
[Link to jira](https://mycore.atlassian.net/browse/MIR-935).
=> MIR-935 marcxml fixes

mir-module/src/main/java/org/mycore/mir/editor/MIRPostProcessor.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-924).
=> MIR-924 abstract improvements

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-2270).
=> MCR-2270 use mods implementation of mycore-csl

mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl, mir-module/src/main/resources/xsl/toc/render-toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-929).
=> MIR-929 Refactor toc layout templates

mir-module/src/main/resources/xsl/metadata/mir-workflow.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-938).
=> MIR-938 improve workflow edit link

mir-module/src/main/resources/config/mir/deprecated.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-2233).
=> MCR-2233 also add deprecated properties to mir-module

mir-module/src/main/resources/xsl/xeditor-mir-templates.xsl
=> merge 2020.06.x

mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl
[Link to jira](https://mycore.atlassian.net/browse/MCR-2281). (Requires https://github.com/MyCoRe-Org/mycore/pull/1066)
=> MCR-2281 use xsl functions for i18n

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-869).
=> MIR-869 Support canonical link

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-2211).
=> MCR-2211 - enable dynamic search field generation, no longer default

mir-module/src/main/resources/xsl/metadata/mir-edit.xsl
... in mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-941).
=> MIR-941 delete include of modsdetails-external.xsl, is already included

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-939).
=> MIR-939 do not include migration commands by default

mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, mir-module/src/main/resources/META-INF/resources/editor/editor-derivate-includes.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-derivate.xed, mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl
a derivate should use mir_access as a classification to restrict access
[Link to jira](https://mycore.atlassian.net/browse/MIR-943).
=> MIR-943 remove support of @display=false for access checks

mir-module/src/main/java/org/mycore/mir/editor/MIREditorUtils.java, mir-module/src/test/java/org/mycore/mir/editor/MIREditorUtilsTest.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-924).
=> MIR-942 possibility to allow attributes in abstract

mir-module/src/main/resources/xsl/xeditor-mir-templates.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-945). Reopen from #537 with new ticket.
=> MIR-945 fix validation output on input-group

mir-module/src/main/resources/xsl/xeditor-mir-templates.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-947).
=> MIR-947 fixed xed-validation-marker check

mir-module/src/main/resources/xsl/mycoreobject-podcast.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-948).
=> MIR-948 Fixed mods:subTitle handling

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-857).
=> MIR-857-Further_information_for_author_search

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-950).
=> MIR-950 Adjusted plumx widget javascript url.

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-952).
=> MIR-952 create data cite v4.3 metadata for doi registration

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-955).
=> MIR-955 use message properties for csl dropdown labels

mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-957).
=> MIR-957 Ensure only first internal mods:genre is used as resourceType

mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-962).
=> add loginlink to i18n no_derivate

mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-959).
=> MIR-959 derivate classification should have higher acl priority

mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-965).
=> MIR-965 datacite-mir prevent exception on multiple his

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
Adapt mir:role.repeated template and generalize queries in
search-entity.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-961).
=> MIR-961-search_entity_does_not_associate_identifier

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-966).
=> MIR-966 Error when adding 0 search hits to the basket

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_details.scss, mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl, mir-module/src/main/resources/xsl/metadata/mods-metadata.xsl, mir-module/src/main/resources/xsl/mir-mods-utils.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-968).
=> MIR-968 add information box for mods:person

mir-cli/src/main/config/acl/defaultrules-commands.txt, mir-module/src/main/java/org/mycore/mir/authorization/MIRKeyStrategyHelper.java, mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/test/java/org/mycore/mir/authorization/MIRStrategyTest.java, mir-module/src/test/resources/MIRStrategyTest/class/mir_access.xml, mir-module/src/test/resources/MIRStrategyTest/class/state.xml, mir-module/src/test/resources/MIRStrategyTest/derivates/mir_derivate_00004711.xml, mir-module/src/test/resources/MIRStrategyTest/derivates/mir_derivate_00004711/test.txt, mir-module/src/test/resources/MIRStrategyTest/objects/mir_mods_00004711.xml, mir-module/src/test/resources/log4j2-test.xml
added basic JUnit tests for MIRStrategy
[Link to jira](https://mycore.atlassian.net/browse/MIR-959).
=> MIR-959 fixed handling of access keys

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss, mir-module/src/main/resources/META-INF/resources/editor/editor-dynamic.xed, mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-autocomplete.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-975).
=> MIR-975 Fixed faulty display of form when linking with internal host

mir-wizard/pom.xml, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardInitSuperuser.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardLoadClassifications.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardMCRCommand.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2100).
Related branch for https://github.com/MyCoRe-Org/mycore/pull/1154
=> MCR-2100 do not use MCRHIBConnection.getSession()

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/cosmol/lib/variables.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/flatmir/lib/variables.scss
Adds some missing !default flags to sass variables.
https://mycore.atlassian.net/browse/MIR-978
=> MIR-978 adds missing default flag to sass variables

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss
[Link to jira](https://mycore.atlassian.net/browse/MIR-976).
=> MIR-976 Added rule that prevents hyphens in author list

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-847).
=> MIR-847 classifications are not indexed after installation

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-980).
=> MIR-980 Query jwt token with user attributes

mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-979).
=> MIR-979 Wrong resourceTypeGeneral for research_data in DataCite-XML

mir-it/src/test/java/org/mycore/mir/it/controller/MIRModsEditorController.java, mir-it/src/test/java/org/mycore/mir/it/controller/MIRSearchController.java, mir-it/src/test/java/org/mycore/mir/it/controller/MIRUserController.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2140).
=> MCR-2140 fixed test to match changes in mycore-xeditor

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-2356).
=> MCR-2356 set submitter as creator role

mir-module/src/main/resources/xsl/mycoreobject-podcast.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-984).
=> MIR-984 Add mods:nonSort to generated title

mir-it/src/test/java/org/mycore/mir/it/controller/MIRUserController.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2368).
=> MCR-2368 fix createUser test case

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/sword/dissemin-mods2mycore-mods.xsl, mir-module/src/main/resources/xsl/sword/mycoreobject2dissemin-status.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-958).
=> MIR-958 use license romeo id and dissem in from deposit

mir-module/src/main/resources/xsl/import/remove-genres.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-987).
=> MIR-987 put validated isbn in identifier tag again

mir-module/src/main/resources/xsl/mycoreobject-podcast.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-988).
=> MIR-988 use name in owner role with email affiliation for itunes:owner

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-990).
=> MIR-990 mir does not build on apple m1 chip

mir-module/src/main/resources/xsl/mods2marcxml.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-999).
=> MIR-999 fix MARCXML output

mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1006).
=> MIR-1006 publications with date issued range generate invalid datacite

mir-module/src/main/resources/META-INF/resources/editor/editor-hosts.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1004).
=> MIR-1004 add article number to metadata view and editor

mir-module/src/main/resources/xsl/mir2schemaOrg.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1009).
=> MIR-1009 add rights_reserved text to schema.org license element

ruleset.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1007).
=> MIR-1007 Extension of the pmd ClassNamingConventions

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-998).
- itemPersonExtendedBox is now used only for handling multiple identifier box
tested:
1) editor-admins.xed as administrator
- person search
- Identifier type add VIAF + GND
- research
- save
- check values in mods structure
2) Tested as submitter (article)
- person search
- Identifier type GND
- save
- check values in mods structure
3) Tested as submitter (sound recording)
- person search 
- Identifier type GND
- research
- subject search
- person search on related Item
- Identifier type GND
- save
- check values in mods structure
4) Tested as submitter (research_results)
- person search
- Identifier type VIAF
- save
- check values in mods structure
=> MIR-998-problems_with_search_entity

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_basket.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_results.scss, mir-module/src/main/resources/xsl/basket-objects.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-994).
Requires https://github.com/MyCoRe-Org/mycore/pull/1214
=> MIR-994 allow export of publication list with a csl style

mir-module/pom.xml, mir-module/src/main/resources/META-INF/resources/content/publish/index.xml, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/pica2mods.xsl, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1013).
=> MIR-1013 use pica2mods library for enrichment resolver

mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/backend/MIRAccessKeyPair.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-992).
=> [MIR-992] Improve Access Key DB Schema - fix

mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyManager.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-992).
=> [MIR-992] Improve Access Key DB Schema - update fix 

mir-cli/src/main/config/acl/defaultrules-commands.txt, mir-it/src/test/java/org/mycore/mir/it/controller/MIRUploadController.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRUploadITCase.java, mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1022).
=> MIR-1022 MIRStrategy does not work right and is not testet

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1023).
=> MIR-1023 do not pass Content-Security-Policy-Header from solr

mir-cli/pom.xml, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1031).
=> MIR-1031 MIR does not run with java 16

mir-module/src/test/java/org/mycore/mir/authorization/MIRStrategyTest.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2415).
=> MCR-2415 adapt MIR to changed api

mir-module/src/main/java/org/mycore/mir/authorization/MIROwnerStrategy.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2424).
=> MCR-2424 adopt MIR and use new class MCRAbstractMetadataVersion

mir-it/src/test/integration/resources/META-INF/persistence.xml, mir-module/src/main/resources/META-INF/mir-module-mappings.xml, mir-module/src/test/resources/META-INF/persistence.xml, mir-wizard/src/main/resources/setup/template-orm.xml, mir-wizard/src/main/resources/setup/template-persistence.xml, mir-wizard/src/test/resources/META-INF/persistence.xml
update persistence.xml versions to 2.2
[Link to jira](https://mycore.atlassian.net/browse/MIR-1038).
=> MIR-1038 fixed entity-mappings

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1040).
=> MIR-1040 solrMirrorURL no longer works for older Solr versions

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/license-filter.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1025).
=> MIR 1025 Option to enable mir_licences explicitly for mir_genres

mir-module/src/main/resources/xsl/metadata/mir-rights.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1041).
=> MIR-1041 mir-rights.xsl slows down metadata page

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/mir/geo-coords.js, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1001).
=> MIR-1001 Improve styling of cartographics/related items

mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1003).
=> MIR-1003 Fixed validation in reletedItem search

mir-module/src/main/resources/xsl/import/scopus2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1042).
=> MIR-1042 exclude abstract from scopus import for license reasons

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1043).
=> MIR-1043 remove "Schlagwort" filter, type:SubjectHeading already do this

mir-it/src/test/integration/resources/META-INF/persistence.xml, mir-wizard/src/main/resources/setup/template-persistence.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1034).
=> MIR-1034 added missing jpa mapping file

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl, pom.xml
- use xslt 3 version of mods utils
- add mandatory attribute relationType to RelatedIdentifier
[Link to jira](https://mycore.atlassian.net/browse/MIR-1053).
=> MIR-1053 - use saxon parser for datacite oai transformation

mir-module/src/main/resources/xsl/datatable.xsl, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl, mir-module/src/main/resources/xsl/metadata/mir-epusta.xsl, mir-module/src/main/resources/xsl/metadata/mir-share.xsl, mir-module/src/main/resources/xsl/response-mir-utils.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1054).
=> MIR-1054 - migrate xs grid classes to default grid class in bs4

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1055).
=> MIR-1055 read short title from csl if available

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1064).
=> MIR-1064 Leave related items with other type unmodified

mir-module/src/main/resources/xsl/mods-dc-meta.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1062).
=> MIR-1062 Duplicate inclusion af abstract as meta tag

mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1063).
=> MIR-1063 Refrain from adding history modal for non-privileged users

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl, mir-module/src/main/resources/xsl/toc/mycoreobject-toc.xsl, mir-module/src/main/resources/xsl/toc/render-toc.xsl, mir-module/src/main/resources/xsl/toc/solr-facets2toc.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc-3.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl, mir-module/src/main/resources/xsl/toc/toc-layouts2solr-json-facet-query.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1052).
=> MIR-1052 Several small issues regarding the TOC

mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
Requires MCR-2512!
[Link to jira](https://mycore.atlassian.net/browse/MIR-1083).
=> MIR-1083 Make use of conditional validation rules

mir-module/src/main/resources/config/mir/deprecated.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1082).
=> MIR-1082 properties for access keys are deprecated

mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1084).
=> MIR-1084 Allow optional inclusion of card footers for layout boxes

mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardLoadClassifications.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1088).
=> MIR-1088 Use URI resolver to load classifications

mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizard.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizardServlet.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizardStartupHandler.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1089).
=> MIR-1089 Automatically execute wizard when a wizard XML file is found

mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizard.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizardRequestFilter.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizardStartupHandler.java
Requires MIR-1089
[Link to jira](https://mycore.atlassian.net/browse/MIR-1090).
=> MIR-1090 inconsistent MIR wizard execution conditions

mir-module/src/main/resources/META-INF/web-fragment.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1093).
=> MIR-1093 enable access key filter for object servlet

mir-module/src/main/resources/xsl/layout/mir-layout-utils.xsl, mir-module/src/main/resources/xsl/mcr_error.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1100).
=> MCR-1100 - fix xsl test, was always true

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1106).
=> MIR-1106 pagination classes are missing in related item select

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1107).
=> MIR-1107 relatedItemSearch search button causes xed debug

mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1075).
=> MIR-1075 Derivate subdirectories should provide better navigation to parent dir

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_results.scss, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1101).
=> MIR-1101 thumbnail derivate should be preferred in search results

mir-module/src/main/resources/catalog.xml, mir-module/src/main/resources/xsd/copyrightMD_schema.xsd
[Link to jira](https://mycore.atlassian.net/browse/MIR-752).
=> MIR-752 add copyrightMD schema to MIR resources

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-autocomplete.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1109).
=> MIR-1109 show title of host or series when searching for relatedItem

mir-it/src/test/java/org/mycore/mir/it/tests/MIRAuthorEditorITCase.java, mir-module/src/main/resources/META-INF/resources/editor/editor-hosts.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1110).
=> MIR-1110 ISBN should not be present in hosts.journal in editor-hosts

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1103).
=> MIR-1103 include access key derivate attributes in jwt

mir-module/src/main/resources/xsl/toc/solr-fields4toc-3.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1114).
=> MIR-1114 fix mir.toc.{host|series}.* field names

.gitmodules, pom.xml
=> Use recommended SOLR for development and the matching solr cores

mir-wizard/src/main/resources/xsl/mir-wizard-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1119).
=> MIR-1119 font awesome is not available in mir wizard

mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1099).
=> Changed hard coded menu name into i18n version

mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/frontend/servlet/MIRAccessKeyServlet.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1102).
=> MIR-1102 switch to access key config methods

mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1122).
=> MIR-1122 Flatten file path on DeepGreen ingest

mir-module/src/main/resources/xsl/sword/jats2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1121).
=> MIR-1121 Fixed incomplete affiliation info on DeepGreen ingest

mir-module/src/main/resources/xsl/sword/jats2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1087).
=> MIR-1087 Fixed dropping empty ORCID iDs on DeepGreen SWORD ingest

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1073).
=> MIR-1073 show create copy or new version if user has create-mods permission

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1123).
=> MIR-1123 enable csv export from solr result list

mir-module/src/main/resources/xsl/mir-solr-3.xsl, mir-module/src/main/resources/xsl/mir-solr.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1124).
=> MIR-1124 Use correct template during name indexing

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/bootstrap4fix.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss
[Link to jira](https://mycore.atlassian.net/browse/MIR-1125).
=> MIR-1125 Fix missing, unfitting and inconsistent form validation styling

mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl
Depends on MIR1052 and MIR-1060!
This is probably the most contentious modifications, because it modifies the structure and appearance of TOC entries and these modifications are likely in need of a discussion. This is why I separated it into a separate PR.
[Link to jira](https://mycore.atlassian.net/browse/MIR-1061).
=> MIR-1061 Volume and issue values should be displayed consistently

mir-module/src/main/resources/config/mir/solr/main/solr-schema.json, mir-module/src/main/resources/xsl/toc/custom-toc-layouts.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc-3.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl
Depends on MIR-1060 and MIR-1061!
[Link to jira](https://mycore.atlassian.net/browse/MIR-1078).
=> MIR-1078 Article numbers should be available for TOC layouts

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1073).
=> MIR-1073 fix show create copy or new version if user has create-mods permission

mir-module/GruntFile.js, mir-module/package.json, mir-module/src/main/resources/META-INF/resources/js/ckeditor-config.js, mir-module/yarn.lock
[Link to jira](https://mycore.atlassian.net/browse/MIR-1097).
=> MIR-1097 Add wordcount plugin for CKEditor 4

mir-module/src/main/resources/META-INF/resources/editor/editor-dynamic.xed, mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1134).
=> MIR-1134 Headings in dynamic editor arn't localized

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1098).
=> MIR-1098 Export license information

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1136).
=> MIR-1136 Allow client side sorting to be skipped for specific search entity types

mir-module/src/main/resources/META-INF/resources/editor/change_genre.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1140).
=> MIR-1140 remove unused sourceUri parameter for xeditor forms

mir-module/src/main/resources/META-INF/resources/js/mir/select-doctype.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1141).
=> MIR-1141 hard coded language values at conent publish page

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl, mir-module/src/main/resources/xsl/mods-seo-meta.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1091).
=> MIR-1091 - Added description html meta tag to metadata page

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
Refacure stylesheet (mods2XMetaDissPlus):
- new choises for monograph, article and thesis
- refacture partOf and dc:source
- implement possiblity to disable templates
https://mycore.atlassian.net/browse/MIR-967
=> MIR-967 - refacture stylesheet; new choices to handle a monograph, article,

mir-it/pom.xml, mir-webapp/pom.xml, pom.xml
updates also jetty and tomcat versions
=> update cargo plugin configuration

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1145).
=> MIR-1145 - issues/MIR-1145-fix-xMetaDissPlus-order

mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1147).
=> MIR-1147 use jwt token to request images if logged in

mir-module/src/main/resources/xsl/toc/solr-fields4toc-3.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1152).
=> MIR-1152: Unusual delimiter between title and subtitle in TOC

mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/basket-objects.xsl, mir-module/src/main/resources/xsl/metadata/mir-export.xsl
Requires [MCR-2642](https://mycore.atlassian.net/browse/MCR-2642).
[Link to jira](https://mycore.atlassian.net/browse/MIR-1144).
=> MIR-1144 Export possibilities are maddeningly confuse

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/ckeditor-config.js, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1130).
=> MIR-1130 Make CKEditor configurable through properties

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[Link to jira](https://mycore.atlassian.net/browse/MCR-2675).
=> MCR-2675 Subtitle separator should be independently styleable

mir-layout/package.json, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/navbar.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/variables.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/cosmol/lib/variables.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/flatmir/lib/variables.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/template.scss.template, mir-layout/yarn.lock
[Link to jira](https://mycore.atlassian.net/browse/MIR-1154).
=> MIR-1154 update bootstrap and bootswatch to 4.6.1

mir-module/src/main/resources/xsl/MARC21slimUtils.xsl, mir-module/src/main/resources/xsl/mods2marcxml.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1160).
=> MIR-1160 change namespace to marc21 and add missing datafield 035/a

mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1162).
=> MIR-1162 add resourceTypeGeneral for software to datacite

mir-cli/src/main/config/acl/webacl-commands.txt, mir-module/src/main/resources/xsl/user.xsl, mir-wizard/src/main/resources/setup/webacl-wizard-commands.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-2710).
=> MCR-2710 Use static URL for password self-change to allow creating specific webpage ACL

mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs, mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[Link to jira](https://mycore.atlassian.net/browse/MCR-2691).
Requires https://github.com/MyCoRe-Org/mycore/pull/1610
=> MCR-2691 allow file renaming

mir-it/pom.xml, mir-module/src/main/java/org/mycore/mir/editor/MIREditorUtils.java, mir-module/src/test/java/org/mycore/mir/editor/MIREditorUtilsTest.java, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1164).
=> MIR-1164 update dependencies

.github/workflows/ci.yml
All builds fail with the message:
`curl: (7) Failed to connect to iweb.dl.sourceforge.net port 443: Connection timed out`
=> Fix bibutils download link

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-2731).
**Only useful in conjunction with https://github.com/MyCoRe-Org/mycore/pull/1662.**
=> MCR-2731 Add configurable list of x-languages that may be edited using the classification editor

mir-it/src/test/integration/resources/META-INF/persistence.xml
Should be merged with https://github.com/MyCoRe-Org/mycore/pull/1660
[Link to jira](https://mycore.atlassian.net/browse/MCR-2728).
=> MCR-2728 remove jpa mapping from mycore-ifs

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1170).
=> MIR-1170 Provide default value to prevent unintentional behavioural change

mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-2530).
=> MCR-2530 add translations

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
=> MIR-1173 use only relatedItems with right type and id

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/log4j2.xml, mir-module/src/main/resources/rules/rules-administrate-users.xml, mir-module/src/main/resources/rules/rules-classes.xml, mir-module/src/main/resources/rules/rules-cli.xml, mir-module/src/main/resources/rules/rules-editor.xml, mir-module/src/main/resources/rules/rules-objects.xml, mir-module/src/main/resources/rules/rules-processing.xml, mir-module/src/main/resources/rules/rules-restapi.xml, mir-module/src/main/resources/rules/rules-sessions.xml, mir-module/src/main/resources/rules/rules-solr.xml, mir-module/src/main/resources/rules/rules-wcms.xml, mir-module/src/main/resources/rules/rules-webpage.xml, mir-module/src/main/resources/rules/rules.xml, mir-module/src/main/resources/xsl/rules-helper.xsl, mir-module/src/test/java/org/mycore/mir/acl/MIRACLTest.java, mir-module/src/test/java/org/mycore/mir/acl/MIRCreateACLTest.java, mir-module/src/test/java/org/mycore/mir/acl/MIRDeleteACLTest.java, mir-module/src/test/java/org/mycore/mir/acl/MIREditorACLTest.java, mir-module/src/test/java/org/mycore/mir/acl/MIRReadObjectACLTest.java, mir-module/src/test/java/org/mycore/mir/acl/MIRSearchACLTest.java, mir-module/src/test/java/org/mycore/mir/acl/MIRTestConstants.java, mir-module/src/test/java/org/mycore/mir/acl/MIRWriteObjectACLTest.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1116).
=> MCR-1116 added rules for new fact based acl system

mir-cli/src/main/config/setup-commands.txt, mir-wizard/src/main/resources/setup/classifications.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1172).
**Relies on https://github.com/MyCoRe-Org/mycore-website/pull/34**
=> MIR-1172 Include the new version of the DINI vocabulary in new MIR instances

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-2752).
=> MCR-2752 use mycore-bom instead of mycore for dependencies

mir-module/src/main/java/org/mycore/mir/authorization/MirSelfRegistrationServlet.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyPairTransformer.java, mir-module/src/main/java/org/mycore/mir/imageware/MIRImageWarePacker.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, ruleset.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-2766).
=> MCR-2766 cleanup pmd rules

.gitignore, README.md, docker-compose.prod.yml
- fixed some errors in README.md
- swap faq and docker section
- added docker-compose section
- added mir-solr container section
=> updated README.md, added docker-compose.prod.yml

mir-module/src/main/resources/META-INF/resources/editor/editor-xml.xed
[Link to jira](https://mycore.atlassian.net/browse/MCR-2732).
Depends on https://github.com/MyCoRe-Org/mycore/pull/1663
=> MCR-2732 Renovate XML editor

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1184).
=> MIR-1184 fixes language nav alignment for abstract view

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/buttons.scss, mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/flatmir/layout.scss, mir-module/src/main/resources/META-INF/resources/js/mir/base.js
Is this the right branch for this feature?
Used the code from kartdok project.
Please tell me if we can use this in this way or 
if it should improved before it can be used in MIR.
[Link to jira](https://mycore.atlassian.net/browse/MIR-1187).
=> MIR-1187 adds button logic to base script and styles to common

.env, Dockerfile, docker-compose.prod.yml, docker-compose.yml, docker-entrypoint.sh, docker-log4j2.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1189).
=> MIR-1189 improve docker containers

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1192).
=> MIR-1192 use new solr-runner-plugin version

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-2784).
=> MCR-2784 Improve display of CC license information

mir-common-resources/src/main/resources/xsl/mycoreobject.xsl, mir-module/src/main/resources/xsl/layout/mycoreobject.xsl, mir-module/src/main/resources/xsl/mir-utils.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1190).
=> MIR-1190 do not use FileContentTypes.xml

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mods2dc.xsl, mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1177).
=> MIR-1177 Allow selection of publication type classification used for xMetaDissPlus and Dublin Core

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-2799).
=> MCR-2799 update tomcat version to 10.1

docker-entrypoint.sh
[Link to jira](https://mycore.atlassian.net/browse/MIR-1196).
=> MIR-1196 docker container startup is very slow

mir-module/src/main/resources/xsl/metadata/mir-video.js.xsl
lets the user select the playback speed of the in-page player by 0.25x increments between 0.5x and 2.0x
[Link to jira](https://mycore.atlassian.net/browse/MIR-1194).
=> MIR-1194 Adjustable Playback-Speed in Media Player

mir-it/src/test/java/org/mycore/mir/it/tests/MIRUserITCase.java
* changed password to subm1tter123 so it does not contain the actural user name
* also fixed missing screenshots and test artifacts
* added test to test the new user validation
[Link to jira](https://mycore.atlassian.net/browse/MIR-1202).
=> MIR-1202 fix user tests password validation

.env, docker-compose.yml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1199.
=> add debug support for docker development

mir-module/src/main/resources/META-INF/resources/editor/editor-genres.xed
=> MIR-1206 Added missing persistent identifier field to some publication types

mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202206Utils.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/editor/xeditor2mods.xsl, mir-webapp/src/main/vue/name-search/src/App.vue
[Link to jira](https://mycore.atlassian.net/browse/MIR-1209).
=> MIR-1209 fix new person editor and add command to fix wrong ids

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1211).
=> MIR-1211 - always ask DataCite even if CrossRef request fails with FATAL

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1210).
=> MIR-1210 add default configuration for access strategy classifications

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1212).
=> MIR-1212 - remove duplicated entry from action menu

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss, mir-module/src/main/resources/xsl/toc/solr-facets2toc.xsl, mir-module/src/main/resources/xsl/toc/toc-layouts2solr-json-facet-query.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1205).
=> MIR-1205 Allow TOC levels with custom display labels

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-2843).
=> MCR-2843 Harmonize periodically perfomed background tasks 

mir-module/src/main/resources/xsl/classsubselect.xsl, mir-module/src/main/resources/xsl/metadata/mir-browse.xsl, mir-module/src/main/resources/xsl/metadata/mir-citation.xsl, mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl, mir-module/src/main/resources/xsl/metadata/mir-file-upload.xsl, mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl, mir-module/src/main/resources/xsl/metadata/mir-viewer.xsl, mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl, mir-module/src/main/resources/xsl/metadata/mods-metadata.xsl, mir-module/src/main/resources/xsl/mir-mods-utils.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/response-mir.xsl, mir-module/src/main/resources/xsl/response-person.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1214).
=> MIR-1214 exclude invalid html namespaces and remove invalid <text> tag

mir-module/src/main/resources/xsl/response-mir.xsl, mir-module/src/main/resources/xsl/response-person.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1214).
=> MIR-1214 delete invalid line break in class attribute and mcrxsl namespace

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1217).
=> MIR-1217 update pica2mods and use gvk as default database

mir-it/src/test/java/org/mycore/mir/it/controller/MIRPublishEditorController.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRAdminEditorITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRComplexSearchITCase.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRUploadITCase.java, mir-module/src/main/resources/META-INF/resources/config/navigation.xml, mir-module/src/main/resources/META-INF/resources/content/publish/index.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1218).
=> MIR-1218 update english version of publication site and fix layout bugs

mir-module/src/main/resources/xsl/mir-mods-utils.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1214).
=> MIR-1214 encode query only not the whole url

mir-it/src/test/java/org/mycore/mir/it/controller/MIRModsEditorController.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1219).
=> MIR-1219 make tests more reliable

mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyPairTransformer.java, mir-module/src/main/java/org/mycore/mir/editor/MIRPostProcessor.java, mir-module/src/main/java/org/mycore/mir/index/MirPathDocumentFactory.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRGoobiIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRSwordMetadataProvider.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-2862).
requires https://github.com/MyCoRe-Org/mycore/pull/1826
=> MCR-2862 changes required for mycore clean-up

mir-module/src/main/resources/META-INF/resources/authorization/new-author.xed, mir-module/src/main/resources/META-INF/resources/content/brand/contact.xml, mir-module/src/main/resources/META-INF/resources/content/brand/impressum.xml, mir-module/src/main/resources/META-INF/resources/content/browse/genres.xml, mir-module/src/main/resources/META-INF/resources/content/browse/institutes.xml, mir-module/src/main/resources/META-INF/resources/content/browse/sdnb.xml, mir-module/src/main/resources/META-INF/resources/content/index.xml, mir-module/src/main/resources/META-INF/resources/content/publish/contract.xml, mir-module/src/main/resources/META-INF/resources/content/publish/guidelines.xml, mir-module/src/main/resources/META-INF/resources/content/publish/importPPN.xml, mir-module/src/main/resources/META-INF/resources/content/publish/index.xml, mir-module/src/main/resources/META-INF/resources/content/search/complex.xed, mir-module/src/main/resources/META-INF/resources/content/search/complex_intern.xed, mir-module/src/main/resources/META-INF/resources/content/search/simple.xed, mir-module/src/main/resources/META-INF/resources/content/search/simple_intern.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1131).
=> Adds title and description tags to metadata of static pages

mir-module/src/main/resources/xsl/mods-seo-meta.xsl
=> MIR-1222 Added metatag title to seo-metadata in html head

mir-module/src/main/resources/META-INF/resources/editor/editor-admins-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1167).
see 8c900b1e61cda57d77aabe82f9835f38bfa20738
=> MIR-1167 activate full name template admin editor

mir-module/src/main/resources/META-INF/resources/editor/editor-admins-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1223).
requires merge or 1c1e6cfda172f582bf6036aba1a111527a3293e3
=> MIR-1223 activate related item template for otherType in admin editor

mir-module/src/main/resources/META-INF/resources/editor/editor-genres.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-hosts.xed, mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
=> MIR-1216 Added genre type issue to editor

mir-cli/src/main/config/setup-commands.txt, mir-wizard/src/main/resources/setup/classifications.xml, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1223).
=> MIR-1223 add classification to setup

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/editor/mir2xeditor.xsl
=> MIR-1193 Made affiliation repeatable

mir-webapp/src/main/vue/name-search/src/App.vue
[Link to jira](https://mycore.atlassian.net/browse/MIR-1232).
=> MIR-1232  person search: do not allow searches for empty string

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1238).
=> MIR-1238 Forced friends aren't real friends

README.md
[Link to jira](https://mycore.atlassian.net/browse/DOC-54).
=> DOC-54 Add documentation notice for mounted volumes and FIX_FILE_SYSTEM_RIGHTS

mir-module/src/main/resources/xsl/import/remove-genres.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1120).
=> MIR-1120 ppn import: remove @otherType if @type is present

mir-module/src/main/resources/xsl/user.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1234).
=> MIR-1234 Attributes not shown as expected

mir-cli/src/main/config/setup-commands.txt, mir-wizard/src/main/resources/setup/classifications.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1237).
=> MIR-1237 Setup classification lists are missing entries

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1240).
=> MIR-1240 websocket does not work with current cargo configuration

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-2895).
requires https://github.com/MyCoRe-Org/mycore/pull/1866
=> MCR-2895 use MCRJobStaticContentGenerator for version related content

mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardDownloadDBLib.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardGenerateJPAConfig.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardGenerateProperties.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardInitDatabase.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardInitSuperuser.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardLoadClassifications.java, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardSolr.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1235).
=> MIR-1235 Exceptions in most wizard commands are silently ignored

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[[Link to jira](https://mycore.atlassian.net/browse/MIR-).](https://mycore.atlassian.net/jira/software/c/projects/MIR/issues/MIR-1245?filter=reportedbyme)
=> MIR-1245 disables dynamic positioning for this dropdown

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1238).
=> MIR-1238 disable forced friends by default

.github/workflows/ci.yml, mir-it/pom.xml, mir-it/src/test/integration/resources/META-INF/persistence.xml, mir-module/src/main/java/org/mycore/mir/MIRClassificationServlet.java, mir-module/src/main/java/org/mycore/mir/index/MirPathDocumentFactory.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202206Utils.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java, mir-module/src/test/resources/META-INF/persistence.xml, mir-wizard/src/main/resources/setup/dbtypes.xml, mir-wizard/src/main/resources/setup/template-persistence.xml, mir-wizard/src/test/resources/META-INF/persistence.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-2647).
Requires https://github.com/MyCoRe-Org/mycore/pull/1587
=> MCR-2647 update to hibernate 6.3 and H2 2.2

mir-module/src/main/resources/META-INF/resources/js/mir/base.js, mir-module/src/main/resources/config/mir/solr/main/solr-config.json
[Link to jira](https://mycore.atlassian.net/browse/MIR-1250).
=> MIR-1250 Set q.alt parameter on /find request handler

mir-module/src/main/resources/xsl/xeditor-custom.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1254).
=> MIR-1254 HTML content not possible in validation messages

mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1251).
=> MIR-1251 Add support for arbitrary classification facets w/o the need for specialized SOLR fields

mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1248).
=> MIR-1248 check if @valueURI contains # - is a classification accordingly

mir-module/src/main/resources/xsl/modsdetails-external.xsl
sorting is done via PI type and than via PI service ID
[Link to jira](https://mycore.atlassian.net/browse/MIR-1257).
=> MIR-1257 sort 'register PI' menu entries

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1231).
reopened https://github.com/MyCoRe-Org/mir/pull/916 as the base branch was set to 2023.06.x
=> MIR-1231 Expect dates in ISO8601 to be in ISO8601 basic format.

docker-log4j2.xml, mir-module/src/main/resources/log4j2.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-3010).
=>  MCR-3010 Duplicate warnings about old absolute include mechanism congest logs 

docker-entrypoint.sh, mir-it/src/test/integration/resources/META-INF/persistence.xml, mir-module/pom.xml, mir-module/src/test/resources/META-INF/persistence.xml, mir-wizard/src/main/resources/setup/dbtypes.xml, mir-wizard/src/main/resources/setup/template-persistence.xml, mir-wizard/src/test/resources/META-INF/persistence.xml, pom.xml
automatically quote database identifier
fix dependencies
[Link to jira](https://mycore.atlassian.net/browse/MCR-2647).
requires https://github.com/MyCoRe-Org/mycore/pull/2024
=> MCR-2647 update database configuration

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
- removed default german translations from js code
- simplified language loading (which fixed the bug)
[Link to jira](https://mycore.atlassian.net/browse/MIR-1158).
=> MIR-1158 Translation of Action and File menu in metadata view is missing

mir-module/src/main/resources/META-INF/resources/js/mir/openaire.js, mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1264).
=> MIR-1264 Slashes in OpenAIRE project IDs are renderd as %2F

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/response-facets.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1270).
=> MIR-1270 Facet values not displayed correctly when SOLR field name differs from classification name

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1271).
=> MIR-1271 Thumbnails not working for derivates with non-PDF main files

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1268).
=> MIR-1268 DINI vocabulary not properly selected in XMDP

mir-module/src/main/resources/xsl/response-facets.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1272).
=> MIR-1272 Allow general and role based exclusion of facets

mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1273).
=> MIR-1273 Updated text in i18n 'mir.accesskey.setInfo'

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1277).
=> MIR-1277 Redirect back to frontpage after login

mir-cli/src/main/config/acl/permissions.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1261).
This commit is already part of main branch but missing in 2023.06.x
=> MIR-1261 add missing permission

mir-module/src/main/resources/config/mir/messages_en.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1281).
=> MIR-1281 Changed English value for mir.accesskey.setOnUser

docker-entrypoint.sh, mir-module/src/main/resources/config/mir/mycore.properties, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizard.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-3031).
requires: https://github.com/MyCoRe-Org/mycore/pull/2052
=> MCR-3031 configure the database without persistence xml

mir-module/src/main/resources/xsl/mir-mods-utils.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1280).
=> MIR-1280 Links from details page to name identifier based name search not working

mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java
Fix aftermath of https://github.com/MyCoRe-Org/mycore/commit/e2ae90c61cbd3b60221b4bd7b43c096320ee0670
=> Fix changed deprecated api of commons compress

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1274).
=> MIR-1274 XMetaDissPlus publication type mapping should rely solely on the mapping defined in classifications

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1269).
=> MIR- Switch to 2022 DINI vocabulary by default

mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1069).
=> MIR-1069 Derivate type classification value should be considered as label

mir-module/src/main/resources/META-INF/resources/config/navigation.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1288).
Requires https://github.com/MyCoRe-Org/mycore/pull/2099 to work as intended.
=> MIR-1288 allow listing of submitted documents for current user

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[MIR-1289](https://mycore.atlassian.net/browse/MIR-1289).
[MIR-1289]: https://mycore.atlassian.net/browse/MIR-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1289 Cancel button redirects to $RequestURL in editor-derivate.xed

mir-module/src/main/resources/xslt/metadata/mods-metadata-page.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1286).
=> MIR-1286 Styling of layout blocks is hampered by missing possiblilty to set classes

mir-module/src/main/resources/xslt/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1294).
=> MIR-1294 wrong include in mycoreobject-datacite-mir.xsl

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
[MIR-1296](https://mycore.atlassian.net/browse/MIR-1296).
[MIR-1296]: https://mycore.atlassian.net/browse/MIR-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1296 Do not allow to select current document as relatedItem

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xslt/metadata/mods-metadata-page.xsl
[MIR-1291](https://mycore.atlassian.net/browse/MIR-1291)
[MIR-1291]: https://mycore.atlassian.net/browse/MIR-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
requires https://github.com/MyCoRe-Org/mycore/pull/2110
=> MIR-1291 Submitters should be enabled to see the history of their records

mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-1301).
=> MIR-1301 fix wrong path to pica stylesheet

mir-module/src/main/java/org/mycore/mir/authorization/MIROwnerStrategy.java, mir-module/src/main/java/org/mycore/mir/sherpa/MCRSherpaProxyResource.java, mir-module/src/test/java/org/mycore/mir/acl/MIRACLTest.java, mir-module/src/test/resources/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MIR-3053).
=> MCR-3053 Redesign API to create configured instances

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1300).
=> MIR-1300 Renaming of files still not possible if a parent directory contains special characters

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1302).
=> MIR-1302 update to current pica2mods release 2.10

mir-cli/src/main/config/acl/webacl-commands.txt, mir-module/src/main/resources/rules/rules-webpage.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1288).
=> MIR-1288 add acl for displaying submitted document

.github/workflows/ci.yml, Dockerfile, mir-it/src/test/java/org/mycore/mir/it/controller/MIRModsEditorController.java, mir-it/src/test/java/org/mycore/mir/it/controller/MIRSearchController.java, mir-it/src/test/java/org/mycore/mir/it/model/MIRAbstract.java, mir-it/src/test/java/org/mycore/mir/it/model/MIRComplexSearchQuery.java, mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/main/java/org/mycore/mir/authorization/MirSelfRegistrationServlet.java, mir-module/src/main/java/org/mycore/mir/authorization/ReCaptcha.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/backend/MIRAccessKey.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/backend/MIRAccessKeyPair.java, mir-module/src/main/java/org/mycore/mir/date/MIRDateConverter.java, mir-module/src/main/java/org/mycore/mir/date/MIRMARCFormatter.java, mir-module/src/main/java/org/mycore/mir/imageware/MIRImageWarePacker.java, mir-module/src/main/java/org/mycore/mir/impexp/MIRClassificationMapper.java, mir-module/src/test/java/org/mycore/mir/editor/MIREditorUtilsTest.java, mir-module/src/test/java/org/mycore/mir/index/MirSolrFileStrategyTest.java, mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202106UtilsTest.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizardStartupHandler.java, mir-wizard/src/test/java/org/mycore/mir/wizard/TestCommands.java, pom.xml, ruleset.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1311).
=> MIR-1311 compile with Java 21

mir-module/src/main/java/org/mycore/mir/editor/MIRPostProcessor.java, mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1310).
=> MIR-1310 abstract and title editor should not leave @altRepGroup

mir-webapp/pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1306).
=> MIR-1306 sword dependencies using javax

mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl
[MIR-1312](https://mycore.atlassian.net/browse/MIR-1312)
[MIR-1312]: https://mycore.atlassian.net/browse/MIR-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1312 Display abstract in the current language of the application

mir-module/src/main/resources/xsl/response-facets.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1316).
=> MIR-1316 Facets not directly linked to classifications lead to unnecessarily cluttered log

mir-module/src/main/resources/config/mir/solr/main/solr-schema.json, mir-module/src/main/resources/xsl/mir-solr-3.xsl, mir-module/src/main/resources/xsl/mir-solr.xsl, mir-module/src/main/resources/xsl/response-mir.xsl
[MIR-1313](https://mycore.atlassian.net/browse/MIR-1313).
[MIR-1313]: https://mycore.atlassian.net/browse/MIR-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1313 Display abstract in search results in the current language of the application.

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mycoreobject-datacite-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1317).
=> Issues/MIR-317 fallback value publication year in Datacite schema

mir-module/src/main/resources/META-INF/resources/js/mir/xeditor-form.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1323).
=> MIR-1323 rejumpToLocationHash breaks editor if el is not defined

mir-wizard/src/main/resources/setup/dbtypes.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1324).
=> MIR-1324 Invalid Maven Central URL for PostgreSQL 

mir-module/src/main/resources/xsl/import/datacite2mods.xsl
[MIR-1319](https://mycore.atlassian.net/browse/MIR-1319)
[MIR-1319]: https://mycore.atlassian.net/browse/MIR-1319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1319 Map rightsList/rights to mods:accessCondition type="use and reproduction" in datacite2mods.xsl

mir-common-resources/src/main/resources/xsl/basket-objects.xsl, mir-common-resources/src/main/resources/xsl/basket.xsl, mir-common-resources/src/main/resources/xsl/mycoreobject.xsl, mir-layout/src/main/resources/xsl/mir-cosmol-layout-utils.xsl, mir-layout/src/main/resources/xsl/mir-flatmir-layout-utils.xsl, mir-module/src/main/resources/xsl/basket-objects.xsl, mir-module/src/main/resources/xsl/classsubselect.xsl, mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl, mir-module/src/main/resources/xsl/layout/mir-layout-utils.xsl, mir-module/src/main/resources/xsl/layout/mir-navigation.xsl, mir-module/src/main/resources/xsl/layout/mycoreobject.xsl, mir-module/src/main/resources/xsl/metadata/mir-browse.xsl, mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl, mir-module/src/main/resources/xsl/mods2oai_dc.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl, mir-module/src/main/resources/xsl/response-mir-utils.xsl, mir-module/src/main/resources/xsl/response-mir.xsl, mir-module/src/main/resources/xsl/response-person.xsl, mir-module/src/main/resources/xsl/response-resultlist.xsl, mir-webapp/src/main/webapp/WEB-INF/web.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-3127).
=> MCR-3127 Drop support for non-cookie based sessions

mir-module/src/main/resources/META-INF/resources/js/mir/base.js
=> MIR-1327 fix insecure request witch blocks site on firefox

mir-module/src/main/resources/META-INF/resources/js/mir/base.js
=> MIR-1327 trim querystring from ppp url

mir-webapp/src/main/vue/editor-tools/package.json, mir-webapp/src/main/vue/editor-tools/src/components/search/search-form.vue, mir-webapp/src/main/vue/editor-tools/yarn.lock
[Link to jira](https://mycore.atlassian.net/browse/MIR-1330).
=> MIR-1330 make editor-tools compatible with node version >= 20

mir-webapp/src/main/vue/name-search/src/api/LobidSearchProvider.ts
[MIR-1339](https://mycore.atlassian.net/browse/MIR-1339).
[MIR-1339]: https://mycore.atlassian.net/browse/MIR-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1339 Obtain ORCID from lobid in xEditor name search

mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1337).
=> MIR-1337 Property to configure display of real name not working as expected

mir-module/src/main/resources/xsl/metadata/mods-metadata.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1338).
=> MIR-1338 missing url encoding in solr query

mir-module/src/main/java/org/mycore/mir/authorization/MirSelfRegistrationServlet.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1335).
=> MIR-1335 Remember self registration date and time

mir-cli/src/main/config/acl/defaultrules-commands.txt, mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardMCRCommand.java, mir-wizard/src/main/resources/setup/defaultrules-wizard-commands.xml, mir-wizard/src/main/resources/setup/restapiacl-wizard-commands.xml, mir-wizard/src/main/resources/setup/webacl-wizard-commands.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1340).
=> MIR-1340 Default ACLs created by CLI and wizard are out of sync and have surprising feature

mir-it/pom.xml, mir-it/src/test/java/org/mycore/mir/it/tests/MIRAdminEditorITCase.java, pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MCR-3134).
Requires https://github.com/MyCoRe-Org/mycore/pull/2224
=> MCR-3134 update to Selenium 4.23.0

mir-layout/src/main/java/org/mycore/mir/viewer/MIRViewerConfigurationStrategy.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-3147).
Requires: https://github.com/MyCoRe-Org/mycore/tree/issues/MCR-3147-modernize_viewer
=> MCR-3147 adopt changes from MCR-3147 modernize viewer

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl, mir-module/src/main/resources/xsl/mycoreobject-migrate-note.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1243).
Requires MyCoRe-Org/mycore#2223
=> MIR-1243 support mods:note with no type or uri attribute

mir-layout/yarn.lock, mir-module/package.json, mir-module/src/main/resources/META-INF/resources/js/ckeditor-config.js, mir-module/yarn.lock, mir-webapp/src/main/vue/editor-tools/package.json, mir-webapp/src/main/vue/editor-tools/yarn.lock, mir-webapp/src/main/vue/name-search/yarn.lock
[Link to jira](https://mycore.atlassian.net/browse/MIR-1344).
Should probably close all current dependabot PRs.
=> MIR-1344 update JavaScript dependencies

mir-module/src/main/resources/xsl/metadata/mir-admindata-box.xsl
[MIR-1348](https://mycore.atlassian.net/browse/MIR-1348)
[MIR-1348]: https://mycore.atlassian.net/browse/MIR-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1348 Provide realm of user in link to profile

mir-layout/src/main/resources/xsl/mir-flatmir-layout-meta-tags.xsl, mir-layout/src/main/resources/xsl/mir-flatmir-layout.xsl
[MIR-1346](https://mycore.atlassian.net/browse/MIR-1346)
[MIR-1346]: https://mycore.atlassian.net/browse/MIR-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1346 Allow to add custom meta elements in mir-flatmir-layout.xsl

mir-module/src/main/java/org/mycore/mir/migration/MIRMigrateStaticHistoryContent.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1354).
=> MIR-1354 Make Count Not Select

mir-layout/src/main/resources/xsl/mir-flatmir-layout.xsl, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/layout/mir-layout-utils.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1305).
depends on https://github.com/MyCoRe-Org/mycore/pull/2131
=> MIR-1305 make xsl stylesheets saxon conform

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[MIR-1355](https://mycore.atlassian.net/browse/MIR-1355)
[MIR-1355]: https://mycore.atlassian.net/browse/MIR-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1355 Support arbitrary number of mods:abstract in tabs

mir-wizard/src/main/resources/setup/defaultrules-wizard-commands.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1350).
**Relies on [MCR-3181](https://github.com/MyCoRe-Org/mycore/pull/2244)**
[MCR-3181]: https://mycore.atlassian.net/browse/MCR-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1350 Loading of permission data not working

README.md
[Link to jira](https://mycore.atlassian.net/browse/MIR-1356).
=> MIR-1356 Improve user instructions, keep beginners in mind!

mir-module/src/main/java/org/mycore/mir/migration/MIRMigrateStaticHistoryContent.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigrateStaticHistoryContentJobAction.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1351).
... and switch over to JobDAO-API while we are at it, ...
=> MIR-1351 Exception thrown when no data exists that can be migrated

mir-module/src/main/resources/xsl/metadata/mir-metadata-box.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1128).
=> MIR-1128 Different order of display of DOI and URN

mir-module/src/main/resources/xsl/metadata/mir-admindata-box.xsl
[MIR-1343](https://mycore.atlassian.net/browse/MIR-1343)
[MIR-1343]: https://mycore.atlassian.net/browse/MIR-1343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1343 Load version history from static xml file (but really)

mir-webapp/src/main/solr/docker-entrypoint.sh
[Link to jira](https://mycore.atlassian.net/browse/MIR-1360).
=> MIR-1360 fix zookeeper is hardcoded in mir solr docker container

mir-module/src/main/resources/META-INF/resources/js/mir/relatedItem-modal.js
[Link to jira](https://mycore.atlassian.net/browse/MIR-1359).
=> MIR-1359 fix choose publication button in related item

pom.xml, ruleset.xml
[Link to PMD rules agreement](https://mycore.atlassian.net/wiki/x/AYBxDw).
=> update PMD ruleset.xml

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[MIR-1408](https://mycore.atlassian.net/browse/MIR-1408)
[MIR-1408]: https://mycore.atlassian.net/browse/MIR-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1408 Added class attributes to list items in action menu

mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1413).
=> MIR-1413 subject xml lang should not be removed

mir-it/src/test/java/org/mycore/mir/it/controller/MIRModsEditorController.java, mir-webapp/src/main/vue/name-search/src/App.vue, mir-webapp/src/main/vue/name-search/src/api/XEditorConnector.ts
- also use mods index and relatedItem index in name attribute to identify input elements, to prevent confusion with name index
[Link to jira](https://mycore.atlassian.net/browse/MIR-1419).
=> MIR-1419-Can't edit author in publication and related item in same xeditor

mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1424).
=> MIR-1424 List of responsible entities is inconsistent in search result page and landing page

mir-module/src/main/resources/xsl/response-facets.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1425).
=> MCR-1425 Externally provided facet labels for dynamic facets

mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyEventHandler.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyManager.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyPairTransformer.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyResolver.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/backend/MIRAccessKey.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/backend/MIRAccessKeyPair.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/package-info.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202106Utils.java, mir-module/src/test/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyManagerTest.java, mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202106UtilsTest.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-1428).
should be considered after https://github.com/MyCoRe-Org/mir/pull/1110.
=> MIR 1428 deprecate outdated mir access key stuff

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_details.scss, mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
[MIR-1437](https://mycore.atlassian.net/browse/MIR-1437).
[MIR-1437]: https://mycore.atlassian.net/browse/MIR-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1437 Display language next to tab title

mir-module/src/main/resources/config/mir/messages_de.properties, mir-module/src/main/resources/config/mir/messages_en.properties, mir-module/src/main/resources/config/mir/messages_it.properties, mir-module/src/main/resources/xsl/metadata/mir-admindata-box.xsl
[MIR-1441](https://mycore.atlassian.net/browse/MIR-1441)
[MIR-1441]: https://mycore.atlassian.net/browse/MIR-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1441 Display proper message to user when history is currently not available

mir-module/src/main/java/org/mycore/mir/MIRClassificationServlet.java, mir-module/src/main/java/org/mycore/mir/MIRStateServlet.java, mir-module/src/main/java/org/mycore/mir/authorization/MIROwnerStrategy.java, mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/frontend/servlet/MIRAccessKeyServlet.java, mir-module/src/main/java/org/mycore/mir/imageware/MIRImageWarePacker.java, mir-module/src/main/java/org/mycore/mir/index/MirPathDocumentFactory.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202206Utils.java, mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java, mir-module/src/main/java/org/mycore/mir/validation/MIRValidationHelper.java, mir-module/src/test/java/org/mycore/mir/authorization/MIRStrategyTest.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizard.java, mir-wizard/src/main/java/org/mycore/mir/wizard/MIRWizardServlet.java, mir-wizard/src/test/java/org/mycore/mir/wizard/TestCommands.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-3348).
=> MCR-3348 fix compile errors

mir-module/src/main/java/org/mycore/mir/imageware/MIRImageWarePacker.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-3359).
=> MCR-3359 MCRAccessException variations should be expresed with proper polymorphism

mir-it/src/test/java/org/mycore/mir/it/controller/MIRSearchController.java, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1362).
=> MIR-1362 fix bug for secondary search form if Solr RequestHandler is not /find

docker-entrypoint.sh, mir-it/src/test/integration/mycore.properties, mir-wizard/src/main/resources/META-INF/resources/wizard/index.xed
[Link to jira](https://mycore.atlassian.net/browse/MCR-3364).
=>  MCR-3364 Simplify Solr authentication architecture

mir-webapp/src/main/vue/name-search/src/api/ViafSearchProvider.ts
[Link to jira](https://mycore.atlassian.net/browse/MIR-1442).
=> MIR-1442-fix VIAF autosuggest request

mir-module/src/main/java/org/mycore/mir/authorization/MirSelfRegistrationServlet.java
[Link to jira](https://mycore.atlassian.net/browse/MIR-3421).
=> MCR-3421 Minor cleanup

mir-module/src/main/resources/xsl/modsdetails-external.xsl
Move the message "show MD5 sums/hide MD5 sums" to the area f…or all users, even unregistered ones
[Link to jira](https://mycore.atlassian.net/browse/MIR-1412).
=> MIR-1412 Show MD5 sum for each file in the derivate file list

mir-module/src/main/resources/META-INF/web-fragment.xml, mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/mir-accesskey-utils.xsl, mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1443).
requires https://github.com/MyCoRe-Org/mycore/pull/2502 and https://github.com/MyCoRe-Org/mir/pull/1128
=> MIR-1443 Use revised access key manager

mir-it/src/test/java/org/mycore/mir/it/controller/MIREditorController.java, mir-it/src/test/java/org/mycore/mir/it/tests/MIRSimpleSearchITCase.java
[Link to jira](https://mycore.atlassian.net/browse/MCR-3412).
Requires https://github.com/MyCoRe-Org/mycore/pull/2515
=> MCR-3412 fix compile errors

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
[Link to jira](https://mycore.atlassian.net/browse/MIR-1448).
=> MIR-1448 Set defineOwnIdentifier prop in App.vue to true based on DOM attribute

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_badges.scss, mir-module/src/main/resources/xsl/badges/mir-badges-date.xsl, mir-module/src/main/resources/xsl/badges/mir-badges-genre.xsl, mir-module/src/main/resources/xsl/badges/mir-badges-license.xsl, mir-module/src/main/resources/xsl/badges/mir-badges-oa.xsl, mir-module/src/main/resources/xsl/badges/mir-badges-state.xsl, mir-module/src/main/resources/xsl/badges/mir-badges-utils.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1453).
=> MIR-1453 improve badge selectors and css

Dockerfile
[Link to jira](https://mycore.atlassian.net/browse/MIR-1460).
=> MIR-1460 Improve tomcat env in Dockerfile

mir-module/src/main/resources/xsl/modsdetails-external.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1463).
=> MIR-1463 editpiroles is not honored in modsdetails-external.xsl

mir-module/src/main/resources/xsl/response-mir.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1464).
- replaced with checkDerivateDisplayPermission
=> MIR-1464 fix checkPermissionForReadingDerivate

Dockerfile
[Link to jira](https://mycore.atlassian.net/browse/MIR-1460).
=> MIR-1460 for security reasons do not pin tomcat version

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[MIR-1449](https://mycore.atlassian.net/browse/MIR-1449)
[MIR-1449]: https://mycore.atlassian.net/browse/MIR-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1449 Correctly map icons to files

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed, mir-module/src/main/resources/xsl/metadata/mir-pdf-errorbox.xsl, mir-module/src/main/resources/xsl/mir-mods-utils.xsl
[MIR-1476](https://mycore.atlassian.net/browse/MIR-1476).
=> MIR-1476 Migrate bootstrap 4 text-left and text-right classes

mir-module/src/main/resources/xsl/badges/mir-badges-state.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1474).
=> MIR-1474 State-badge causes error, when state-field is missing in Solr data

mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java, mir-module/src/main/java/org/mycore/mir/imageware/MIRImageWarePacker.java, mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java, mir-module/src/main/resources/config/mir/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/MCR-3375).
**Depends on https://github.com/MyCoRe-Org/mycore/pull/2467**
=> MCR-3375 changes required by mycore changes

mir-module/src/main/resources/META-INF/resources/js/mir/ror-search.js
[MIR-1481](https://mycore.atlassian.net/browse/MIR-1481).
[MIR-1481]: https://mycore.atlassian.net/browse/MIR-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1481 Reflect recent ROR api changes

mir-module/src/main/resources/xsl/toc/solr-fields4toc-3.xsl, mir-module/src/main/resources/xsl/toc/solr-fields4toc.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1479).
=> MIR-1479 Indexing of TOC fields fails when multiple mods:number elements are present in the same mods:detail element

mir-module/src/main/resources/config/mir/mycore.properties, mir-module/src/main/resources/xsl/import/complexify-crossref-json-xml.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-1484).
=> MCR-1484 Multiple titles are concatenated into singe title when importing metadata from Crossref

pom.xml
[Link to jira](https://mycore.atlassian.net/browse/MIR-1485).
=> MIR-1485-mir-2022-06-x-does-use-wrong-mycore-2022-06-x-version

mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
[MIR-1488](https://mycore.atlassian.net/browse/MIR-1488).
[MIR-1488]: https://mycore.atlassian.net/browse/MIR-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIR-1488 Fixed calculation of pagination.end for last page of pagination
