pom.xml

reorder modules so that mir-cli is build before mir-wizard

MCR-526 Git-Migration

---

mir-module/src/main/resources/xsl/xeditor-mir-templates.xsl

- replaced german and english text with i18n key (mir.select)

MIR-552 use i18n key for empty select option

---

mir-module/src/main/resources/xsl/editor/xeditor2mods.xsl

structure/parents/parent needs to be present before handing over to
`MCRMetadataManager`.

MIR-549 add parent in post-processor

---

mir-module/src/main/resources/config/mir/mycore.properties

changed nbn-resolving.org to nbn-resolving.de

MIR-573 URN Resolver URL does not redirect directly

---

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl

- added template for x-place which combines name, place and address
- use "|" as delimiter, {name} | {place} | {address} , e.g. "Friedrich-Schiller-Universität Jena | Jena | Fürstengraben 1, 07743 Jena"
- address is optional, without an address, place is used as address
- uses mods:publisher and mods:placeTerm before using classification

MIR-603 add x-address and x-place to mir-institutes for xMetaDissPlus

---

mir-module/package.json
mir-module/yarn.lock

- switched to harmony branch of grunt-contrib-uglify

MIR-617 use the harmony branch of grunt-contrib-uglify for ES6

---

mir-module/pom.xml
pom.xml

Add levigo-jbig2-imageio as runtime dependency

MIR-543 missing runtime dependency to jbig2-imageio

---

mir-module/src/main/resources/xsl/metadata/mir-viewer.xsl

The framed viewer now uses pdfCreatorFormatString and
pdfCreatorRestrictionFormatString

MIR-633-Framed_MyCoRe_Viewer_does_not_work

---

mir-module/src/main/resources/config/mir/mycore.properties
mir-webapp/src/main/resources/mycore.properties

Old properties where in classpath. Support for this was dropped
whene MCR-1649 dropped mycore-complete support.

MCR-1649 move properties to mir-module

---

mir-module/src/main/resources/config/mir/mycore.properties
mir-module/src/main/resources/xsl/mcr_directory-recursive.xsl
mir-module/src/main/resources/xsl/mods2dc.xsl
mir-module/src/main/resources/xsl/mods2epicur.xsl
mir-module/src/main/resources/xsl/mods2oai_dc.xsl
mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl

The stylesheet could be optimized:
Always trust the metadata
Do not query external systems like GND
Do not query mycore-pi
Do not traverse the tree if not needed and use XSL contexts
Support multiple derivates per document
Resolve derivates only once
Do not use hidden derivates
Resolve all directories and files and not only to top directory
Use Muenchian Method to get content types
Language classification is loaded once and use xsl:key to search for categories
Use marcrelator classification to get creator and contributor roles

MIR-657 make OAI answers DINI conform and optimize for speed

---

mir-module/src/main/resources/xsl/mods2dc.xsl
mir-module/src/main/resources/xsl/mods2oai_dc.xsl

choose of 'info:eu-repo/semantics/*' is exclusive
dc:rights from classification works with every classification
dc:rights content should be english if english labels are present

MIR-676 fixed dc:rights

---

mir-module/GruntFile.js
mir-module/package.json
mir-module/src/main/resources/xsl/metadata/mir-video.js.xsl
mir-module/yarn.lock

- get videojs with yarn on build time
- updated videojs to 6.4.0
- updated videojs-contrib-hls to 5.12.2

MIR-698 load videojs with yarn on build time

---

mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl

we can use shariff.min.css
[Link to jira](https://mycore.atlassian.net/browse/MIR-788).

MIR-788 shariff is now compatible with our fontawesome version

---

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/forms.scss
mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss
mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/user-login.scss
mir-module/src/main/resources/xsl/layout/mir-navigation.xsl
mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
mir-module/src/main/resources/xsl/metadata/mir-citation.xsl
mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl
mir-module/src/main/resources/xsl/xeditor-mir-templates.xsl

Fixes minor layout issues, caused by bootstrap 4:
- removed global margin right from buttons, caused by an outdated css class and custom rule
- fixes side effect by adding space to login buttons
- repairs the modal dialogue for document version history e.g.

MIR-842 copy current issue url fix layout issues caused by bootsrap 4 migration

---

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/base.scss

Added a IE11 fix for the sticky footer.
IE11 has other defaults for flexbox items.
Furthermore, IE11 did not know min-height.
Solution:
- used the long notation for the flex box item to prevent wrong defaults
- changed the min-height to height because IE11 do not support min-height
- set explicit the shrink behaviour of header and footer
[Link to jira](https://mycore.atlassian.net/browse/MIR-852).

MIR-852 Adds IE11 fix for sticky footer

---

mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js

[Link to jira](https://mycore.atlassian.net/browse/MIR-841).
agreed correction:
-> Support actively one ifentifer for one authority file organisation
The UI should only support a new nameidentifier input field creation if the maintained authority file organisation has not been selected already.

MIR-841 adjust handling multiple ids in admineditor

---

mir-module/pom.xml

removes dirty flag from bamboo builds
[Link to jira](https://mycore.atlassian.net/browse/MIR-883).

MIR-883 update git-commit-id-plugin

---

mir-module/src/main/resources/xsl/response-mir.xsl

[Link to jira](https://mycore.atlassian.net/browse/MIR-901).
Added a parameter for basket link template.
It determines if the drop down class is needed.
This fix a layout issue caused by the drop down class if there is no drop down menu.

MIR-901 adds parameter to determine if dropdown class is needed

---

mir-layout/src/main/resources/xsl/mir-cosmol-layout-utils.xsl
mir-layout/src/main/resources/xsl/mir-flatmir-layout-utils.xsl
mir-module/src/main/resources/config/mir/mycore.properties
mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl
mir-module/src/main/resources/xsl/metadata/mir-abstract.xsl
mir-module/src/main/resources/xsl/mir-utils.xsl
mir-module/src/main/resources/xsl/response-mir-utils.xsl
mir-module/src/main/resources/xsl/response-mir.xsl
mir-module/src/main/resources/xsl/response-person.xsl

make allowed roles for search in non published documents configurable, using new property MIR.OwnerStrategy.AllowedRolesForSearch
[Link to jira](https://mycore.atlassian.net/browse/MIR-934).

MIR-934 make allowed roles for search in non published documents

---

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl

added genre article to isPartOf
[Link to jira](https://mycore.atlassian.net/browse/MIR-956).

MIR-956 xMetaDissPluss should use dcterms:isPartOf

---

mir-module/src/test/resources/mycore.properties

[Link to jira](https://mycore.atlassian.net/browse/MIR-847).

MIR-847 do not use MCRSolrCategoryDAO in jUnitTests

---

mir-module/src/test/java/org/mycore/mir/authorization/MIRStrategyTest.java
mir-module/src/test/resources/MIRStrategyTest/class/mcr-roles.xml

NOTE: requires to define rule mapping for ID "derivate:mir_access:accessKey"
[Link to jira](https://mycore.atlassian.net/browse/MIR-985).

MIR-985 add extended test to check accesskey fallbackrule for derivates

---

mir-module/src/main/resources/xsl/sword/jats2mods.xsl

fixed jats2mods.xsl
[Link to jira](https://mycore.atlassian.net/browse/MIR-986).

MIR-986 Can not import DeepGreen

---

mir-module/src/main/resources/META-INF/resources/editor/editor-admins-includes.xed
mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed

Added a repeatable version of the coordinates, it is activated by default in admin editor. 
[Link to jira](https://mycore.atlassian.net/browse/MIR-991).

MIR-991 geocoords javascript doesn't work with more than on coordinates entry

---

mir-module/src/main/resources/xsl/metadata/mir-citation.xsl

The value selection in the otherwise block was not working.
I've changed the selection to classification request so that text
description is used in the otherwise case.
[Link to jira](https://mycore.atlassian.net/browse/MIR-1030).

MIR-1030 Fixed display of licenses in the info box

---

mir-module/src/main/resources/META-INF/resources/editor/editor-includes.xed
mir-module/src/main/resources/config/mir/mycore.properties

Added a new mycore property which makes it possible to exclude genre types
from xeditor validation.
[Link to jira](https://mycore.atlassian.net/browse/MIR-1035).

MIR-1035 Exclude genre types from validation

---

mir-module/src/main/resources/config/mir/mycore.properties
mir-module/src/main/resources/xsl/metadata/mods-metadata-page.xsl

[Link to jira](https://mycore.atlassian.net/browse/MIR-1047).
Depends upon [MCR-2464](https://github.com/MyCoRe-Org/mycore/pull/1320).
This pull request only adds the option to include icons in panels rendered by the new Metadata Layout. Actually using this feature requires changes to the configuration. Example configuration is provided but commented out, so the default behavior of MIR is unaffected.

MIR-1047 Add option to include icon in panels rendered by the new Metadata Layout

---

mir-module/src/main/resources/xsl/layout/mir-common-layout.xsl

Not sure, is this the correct branch to fix?
xasia seems to run on 2020.06

MIR-1081 fixes lost classes when dropdown menu entry gets active

---

README.md

The link to documentation page was old and not correct any more. I corrected the link current MIR install page.

Fixed wrong link to the documentation page

---

mir-module/src/main/java/org/mycore/mir/orcid/MIROrcidServlet.java

JSON sent over the internet must be encoded as UTF-8 as per RFC 8259.
This commit changes the character encoding of the MIROrcidServlet from
ISO-8859-1 to UTF-8, fixing the display of special characters in the
browser.
[Link to jira](https://mycore.atlassian.net/browse/MIR-1142).

MIR-1142 Change MIROrcidServlet character encoding to UTF-8

---

mir-module/src/main/resources/xsl/mods2xMetaDissPlus.xsl

should only contain ASCII characters according to DNB (undocumented)
[Link to jira](https://mycore.atlassian.net/browse/MIR-1143).

MIR-1143 - XMetaDissPlus transfer url should only contain ASCII characters

---

mir-module/src/main/java/org/mycore/mir/MIRGetOpenAIREProjectsServlet.java

Make MIRGetOpenAIREProjectsServlet use the global proxy set via Java's
system properties ("https.proxyHost" etc.) when it constructs its Apache
HTTP Client.
[Link to jira](https://mycore.atlassian.net/browse/MIR-1149).

MIR-1149 Use global proxy for OpenAIRE

---

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_metadata.scss

[Link to jira](https://mycore.atlassian.net/browse/MIR-1156).

MIR-1156 Unnecessary margin causes premature line breaks

---

README.md
mir-wizard/src/main/java/org/mycore/mir/wizard/command/MIRWizardDownloadDBLib.java
mir-wizard/src/main/resources/config/mir-wizard/mycore.properties
mir-wizard/src/main/resources/setup/template-persistence.xml
mir-wizard/src/main/resources/xsl/wizard-orm.xsl

- use MCRConfigurationDirSetup.loadExternalLibs() instead of reflection to load new driver lib
- fixed generated persistence.xml
- updated README.md to use tomcat instead of jetty
[Link to jira](https://mycore.atlassian.net/browse/MIR-1175).

MIR-1175 repair MIR-Wizard

---

mir-module/src/main/resources/xsl/mods2dc-mode-dc.xsl
mir-module/src/main/resources/xsl/mods2dc.xsl

change the mods2dc stylesheets to use "/" iso date separators
[Link to jira](https://mycore.atlassian.net/browse/MIR-1183).

MIR-1183 mod2dc.xsl coverage ranges should use iso format

---

mir-module/src/main/resources/xsl/response-mir.xsl

[Link to jira](https://mycore.atlassian.net/browse/MIR-1174).
**This is not en elegant solution**, but AFAICS an elegant solution would require a major rewrite (that doesn't rely on a string-based analysis of the request URL).
Seeing that this stylesheet heavily relies on the use of Xalan-extension, I think it is up for a major rewrite anyway, when MIR is updated to use only XSLT 3.0. I don't think its worth the time to invest heavily in this stylesheet in the meantime.

MIR-1174: Deselecting of a facet value is impossible after page traversal

---

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/navbar.scss
mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/variables.scss
mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/flatmir/lib/navbar.scss
mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/flatmir/lib/variables.scss

[Link to jira](https://mycore.atlassian.net/browse/MIR-1197).
- moves navlink fix to flatly section
- extends the fix to enable bootstrap navlink settings again
- enables the settings for navbars without the bg-primary class

MIR-1197 improves fix of the flatly navlink

---

mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java
mir-module/src/main/resources/config/mir/mycore.properties
mir-module/src/main/resources/xsl/sword/jats2mods.xsl

- update jats2mods.xsl to xslt 3
- use oa_nlz only as default
- fixed solr query for ISSN
- fixed empty contrib-id
- changed mods:dateIssued to w3cdtf
- improved license parsing
[Link to jira](https://mycore.atlassian.net/browse/MIR-1213).

MIR-1213 update jats2mods.xsl to xslt 3 and add thulb fixes

---

mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java
mir-module/src/main/java/org/mycore/mir/sword2/MIRGoobiIngester.java
mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java

use MCRMetadataManager.getMCRObjectIDGenerator().getNextFreeId(...) in mir-module
[Link to jira](https://mycore.atlassian.net/browse/MCR-2909).

MCR-2909 replaced deprecated method calls

---

.github/workflows/ci.yml
mir-module/src/main/resources/META-INF/resources/js/mir/citation.js
mir-module/src/main/resources/xsl/metadata/mir-citation.xsl

[Link to jira](https://mycore.atlassian.net/browse/MIR-1246).

MIR-1246 MIR.defaultCitationStyle should not be ignored

---

mir-module/src/main/resources/xsl/editor/mods2xeditor.xsl

[Link to jira](https://mycore.atlassian.net/browse/MIR-1247).

MIR-1247 add filter for additional mods:role and mods:roleTermin

---

mir-module/src/main/java/org/mycore/mir/sword2/MIRDeepGreepIngester.java

- upload all files from zip
- set pdf with same name as metadata xml as mainfile
[Link to jira](https://mycore.atlassian.net/browse/MIR-1249).

MIR-1249 DeepGreen wrong pdf uploaded

---

mir-module/src/main/resources/xsl/import/datacite2mods.xsl
mir-module/src/main/resources/xsl/strip-namespaces.xsl

[MIR-1292](https://mycore.atlassian.net/browse/MIR-1292) and [MIR-1293](https://mycore.atlassian.net/browse/MIR-1293).
requires https://github.com/MyCoRe-Org/mycore/pull/2105
[MIR-1292]: https://mycore.atlassian.net/browse/MIR-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MIR-1293]: https://mycore.atlassian.net/browse/MIR-1293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MIR-1292 MIR-1293 Updated template datacite2mods.xsl to support ORCID ids given by url

---

.github/workflows/ci.yml
docker-compose.prod.yml
docker-compose.yml
mir-it/src/test/java/org/mycore/mir/it/tests/MIRITBase.java
mir-module/pom.xml
mir-module/src/main/java/org/mycore/mir/MIRGetOpenAIREProjectsServlet.java
mir-module/src/main/java/org/mycore/mir/authorization/ReCaptcha.java
mir-webapp/src/main/solr/Dockerfile
mir-webapp/src/main/solr/docker-entrypoint.sh
mir-webapp/src/main/solr/solr.xml
mir-webapp/src/main/solr/zoo.cfg
pom.xml

[Link to jira](https://mycore.atlassian.net/browse/MCR-2134).
Requires https://github.com/MyCoRe-Org/mycore/pull/2212

MCR-2134 update dependencies

---

mir-it/src/test/java/org/mycore/mir/it/controller/MIRUserController.java
mir-module/pom.xml
mir-module/src/main/resources/xsl/metadata/mir-admindata-box.xsl
mir-module/src/main/resources/xsl/modsdetails-external.xsl
mir-module/src/main/resources/xsl/user.xsl
mir-module/src/main/resources/xslt/metadata/mods-metadata-page.xsl

[MIR-1336](https://mycore.atlassian.net/browse/MIR-1336).
[MIR-1336]: https://mycore.atlassian.net/browse/MIR-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MIR-1336 Display realname of creator/modifier in mir-admin-box

---

mir-module/src/main/resources/config/mir/mycore.properties
mir-module/src/main/resources/xsl/metadata/mir-collapse-files.xsl

[Link to jira](https://mycore.atlassian.net/browse/MIR-1347).

MIR-1347-allow to change the number of entries per page of the filebox with a property

---

.github/workflows/ci.yml

https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

fix github actions

---

docker-entrypoint.sh

[Link to jira](https://mycore.atlassian.net/browse/MIR-1353).

MIR-1353-wrong command in docker migration function

---

mir-layout/src/main/resources/META-INF/resources/mir-layout/scss/common/mir_browse.scss
mir-module/src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs
mir-module/src/main/resources/META-INF/resources/js/mir/base.js
mir-module/src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
mir-module/src/main/resources/config/mir/messages_de.properties
mir-module/src/main/resources/config/mir/messages_en.properties
mir-module/src/main/resources/config/mir/messages_it.properties
mir-module/src/main/resources/xsl/modsdetails-external.xsl

The list of derivate files should have the ability to display the MD5 amount
[MIR-1412](https://mycore.atlassian.net/browse/MIR-1412).
[MIR-1412]: https://mycore.atlassian.net/browse/MIR-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MIR-1412 Show MD5 sum for each file in the derivate file list

---

mir-module/pom.xml
mir-module/src/main/java/org/mycore/mir/authorization/accesskeys/MIRAccessKeyPairTransformer.java
mir-module/src/main/resources/config/mir/mycore.properties

use property MIR.AccessKey.JAXBContextFactory to override default
[Link to jira](https://mycore.atlassian.net/browse/MIR-1416).
This pull request includes significant changes to the `mir-module` to enhance the JAXB context initialization and dependency management. The most important changes include adding a new dependency, updating the JAXB context initialization, and modifying the unmarshalling process.
* Added `jaxb-runtime` dependency to the `pom.xml` file to handle JAXB operations at runtime.
* Updated the `MIRAccessKeyPairTransformer` class to use `JAXBContextFactory` for creating JAXB contexts. This change involves fetching the factory instance from the configuration and using it to create the context.
* Modified the `buildAccessKeyPair` method in `MIRAccessKeyPairTransformer` to …

MIR-1416 pin glassfish jaxb-runtime to MIRAccessKeyPairTransformer

---

mir-cli/src/main/config/acl/webacl-commands.txt
mir-module/src/main/resources/META-INF/resources/config/navigation.xml
mir-module/src/main/resources/config/mir/mycore.properties
mir-module/src/main/resources/rules/rules-processing.xml
mir-wizard/src/main/resources/setup/webacl-wizard-commands.xml

* remove old processingGUI.xsl references
* remove rules to protect xsl website
* fix link
[Link to jira](https://mycore.atlassian.net/browse/MIR-1420).

MIR-1420 use new processing ui

---

mir-module/src/main/resources/config/mir/mycore.properties
mir-wizard/src/main/resources/config/mir-wizard/mycore.properties

[Link to jira](https://mycore.atlassian.net/browse/MIR-1430).
This pull request includes several changes to the `mir-module/src/main/resources/config/mir/mycore.properties` file, primarily focusing on the replacement of specific TransformerFactoryClass implementations with placeholders. These changes aim to improve configurability and maintainability.
Replacement of TransformerFactoryClass implementations:
* Replaced `org.apache.xalan.processor.TransformerFactoryImpl` with `%XALAN%` for multiple content transformers. [[1]](diffhunk://#diff-3192279bae14a2ab86afc48d0b5b33fa96f3a7ea0ea51f2e526e61f67f3f78f6L21-R21) [[2]](diffhunk://#diff-3192279bae14a2ab86afc48d0b5b33fa96f3a7ea0ea51f2e526e61f67f3f78f6L49-R72)
* Replaced `net.sf.saxon.TransformerFactoryImpl` with `%SAXON%` for various content …

MIR-1430 use %SAXON% and %XALAN% for simpler configuration

---

mir-it/src/test/java/org/mycore/mir/it/controller/MIRSearchController.java
mir-layout/src/main/resources/xsl/mir-flatmir-layout-utils.xsl
mir-module/src/main/resources/META-INF/resources/js/mir/base.js
mir-module/src/main/resources/xsl/response-mir.xsl

The second search is currently not working. It should take the initial query from the main search and form a query based on the combination of the search string and the filter type for the query
[Link to jira](https://mycore.atlassian.net/browse/MIR-1362).

MIR-1362 Result filter displayed on top of search results ignores "df"-Parameter

---

.github/workflows/ci.yml

fixes:
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

Update CI setup
